// Generated Help Map file.
// Commands (ID_* and IDM_*)
#define HID_OK                                  0x10647
#define HID_FILE_SAVEGRAPHAS                    0x18003
#define HID_VIEW_ZOOMIN                         0x18004
#define HID_VIEW_ZOOMOUT                        0x18005
#define HID_MENUHELP                            0x1800D
#define HID_MENUEXIT                            0x1800E
#define HID_VIEW_COMPAREREVISIONS               0x1800F
#define HID_VIEW_COMPAREHEADREVISIONS           0x18010
#define HID_VIEW_UNIFIEDDIFF                    0x18011
#define HID_VIEW_UNIFIEDDIFFOFHEADREVISIONS     0x18012
#define HID_VIEW_SHOWALLREVISIONS               0x1801C
#define HID_VIEW_GROUPBRANCHES                  0x1801F
#define HID_REVGRAPH_ZOOMCOMBO                  0x18020
#define HID_VIEW_ZOOM100                        0x18021
#define HID_VIEW_ZOOMHEIGHT                     0x18022
#define HID_VIEW_ZOOMWIDTH                      0x18023
#define HID_VIEW_ZOOMALL                        0x18024
#define HID_FILE_SAVESTATGRAPHAS                0x18026
#define HID_FILTER_EXCLUDEPATHS                 0x18027
#define HID_FILTER_EXCLUDEREVISIONS             0x18028
#define HID_VIEW_FILTER                         0x18029
#define HID_VIEW_SHOWOVERVIEW                   0x1802D
#define HID_VIEW_TOPDOWN                        0x1802E
#define HID_URL_FOCUS                           0x1802E
#define HID_VIEW_SHOWHEAD                       0x1802F
#define HID_REFRESHBROWSER                      0x1802F
#define HID_VIEW_EXACTCOPYSOURCE                0x18030
#define HID_INLINEEDIT                          0x18030
#define HID_VIEW_SHOWDIFFPATHS                  0x18031
#define HID_VIEW_FOLDTAGS                       0x18032
#define HID_VIEW_REDUCECROSSLINES               0x18033
#define HID_VIEW_REMOVEDELETEDONES              0x18034
#define HID_VIEW_SHOWTREESTRIPES                0x18035
#define HID_VIEW_TOPALIGNTREES                  0x18036
#define HID_LOGDLG_REFRESH                      0x18037
#define HID_LOGDLG_FIND                         0x18038
#define HID_LOGDLG_FOCUSFILTER                  0x18039
#define HID_VIEW_SHOWWCREV                      0x1803A
#define HID_DELETEBROWSERITEM                   0x1803D
#define HID_VIEW_REMOVEUNCHANGEDBRANCHES        0x1803E
#define HID_VIEW_SHOWWCMODIFICATION             0x1803F
#define HID_VIEW_REMOVETAGS                     0x18040
#define HID_URL_UP                              0x18043
#define HID_NEW_EXECUTABLE                      0x18047
#define HID_EDIT_DEFAULT                        0x1804A
#define HID_NEW_NEEDSLOCK                       0x1804D
#define HID_NEW_MIMETYPE                        0x1804F
#define HID_EDIT_ADVANCED                       0x18050
#define HID_NEW_ADVANCED                        0x18051
#define HID_NEW_BUGTRAQ                         0x18052
#define HID_NEW_EOL                             0x18053
#define HID_NEW_KEYWORDS                        0x18054
#define HID_NEW_EXTERNALS                       0x18055
#define HID_NEW_LOGSIZES                        0x18056
#define HID_NEW_LANGUAGES                       0x18057
#define HID_NEW_LOCALHOOKS                      0x1805D
#define HID_URL_HISTORY_BACK                    0x1805E
#define HID_URL_HISTORY_FORWARD                 0x1805F
#define HID_NEW_MERGELOGTEMPLATES               0x18061
#define HID_LOGDLG_MONITOR_CHECKREPOSITORIESNOW 0x18062
#define HID_LOGDLG_MONITOR_ADDPROJECT           0x18063
#define HID_LOGDLG_MONITOR_EDIT                 0x18064
#define HID_LOGDLG_MONITOR_REMOVE               0x18065
#define HID_MISC_OPTIONS                        0x18066
#define HID_MISC_MARKALLASREAD                  0x18067
#define HID_LOGDLG_MONITOR_THREADFINISHED       0x18068
#define HID_POPUP_SHOWMONITOR                   0x18069
#define HID_POPUP_EXIT                          0x1806A
#define HID_MISC_UPDATE                         0x1806B
#define HID_LOGDLG_MONITOR_ADDSUBPROJECT        0x1806C
#define HID_POPUP_UPDATEALL                     0x1806D
#define HID_LOGDLG_MONITOR_CLEARERRORS          0x1806E
#define HID_LOGDLG_MONITOR_CHECKNOW             0x1806F
#define HID_LOGDLG_COPYREVISIONS                0x18070
// Prompts (IDP_*)
// Resources (IDR_*)
#define HIDR_MAINFRAME                          0x20001
#define HIDR_REVISIONGRAPH                      0x200B7
#define HIDR_ACC_REVISIONGRAPH                  0x200B9
#define HIDR_REVGRAPHBAR                        0x200DF
#define HIDR_REVGRAPHGLYPHS                     0x200E0
#define HIDR_STATGRAPH                          0x200EB
#define HIDR_ACC_REPOBROWSER                    0x200FD
#define HIDR_ACC_LOGDLG                         0x200FE
#define HIDR_PROPNEWMENU                        0x20136
#define HIDR_PROPEDITMENU                       0x20137
#define HIDR_MONITORTRAY                        0x2016D
#define HIDR_HELPALIAS                          0x2018C
#define HIDR_HELPCONTEXT                        0x2018D
// Dialogs (IDD_*)
#define HIDD_SETTINGSPROXY                      0x20066
#define HIDD_SETTINGSHOOKS                      0x20067
#define HIDD_SETTINGSOVERLAY                    0x2006A
#define HIDD_SETTINGSSAVEDDATA                  0x2006C
#define HIDD_MERGEWIZARD_START                  0x2006D
#define HIDD_MERGEWIZARD_TREE                   0x2006E
#define HIDD_MERGEWIZARD_OPTIONS                0x2006F
#define HIDD_ABOUT                              0x20081
#define HIDD_LOGMESSAGE                         0x20082
#define HIDD_PROMPT                             0x20083
#define HIDD_CHECKOUT                           0x20085
#define HIDD_SVNPROGRESS                        0x20086
#define HIDD_COMMITDLG                          0x20087
#define HIDD_IMPORT                             0x2008B
#define HIDD_SWITCH                             0x2008C
#define HIDD_COPY                               0x2008E
#define HIDD_SETTINGSMAIN                       0x2008F
#define HIDD_RENAME                             0x20097
#define HIDD_UPDATE                             0x20098
#define HIDD_REPOSITORY_BROWSER                 0x20099
#define HIDD_ADD                                0x2009B
#define HIDD_RELOCATE                           0x2009D
#define HIDD_CHANGEDFILES                       0x2009E
#define HIDD_SIMPLEPROMPT                       0x200A0
#define HIDD_INPUTDLG                           0x200A1
#define HIDD_BLAME                              0x200A2
#define HIDD_URL                                0x200A4
#define HIDD_SETTINGSPROGSADV                   0x200AA
#define HIDD_TOOLASSOC                          0x200AB
#define HIDD_REVISION                           0x200AD
#define HIDD_CHECKFORUPDATES                    0x200AE
#define HIDD_REVERT                             0x200AF
#define HIDD_PROPERTIES                         0x200B1
#define HIDD_STATGRAPH                          0x200B3
#define HIDD_REVISIONGRAPH                      0x200B6
#define HIDD_OVERLAYICONS                       0x200B8
#define HIDD_SETOVERLAYICONS                    0x200B8
#define HIDD_LOCK                               0x200BF
#define HIDD_SETTINGSPROGSDIFF                  0x200C0
#define HIDD_SETTINGSPROGSMERGE                 0x200C1
#define HIDD_SETTINGSLOOKANDFEEL                0x200C3
#define HIDD_SETTINGSDIALOGS                    0x200C4
#define HIDD_SETTINGSWIN11CONTEXTMENU           0x200C5
#define HIDD_DIFFFILES                          0x200C7
#define HIDD_SHELVE                             0x200CD
#define HIDD_UNSHELVE                           0x200CE
#define HIDD_RESOLVE                            0x200CF
#define HIDD_CREATEPATCH                        0x200D0
#define HIDD_HISTORYDLG                         0x200D3
#define HIDD_SETTINGSCOLORS                     0x200D4
#define HIDD_SETTINGSMISC                       0x200D5
#define HIDD_EDITPROPERTIES                     0x200E2
#define HIDD_EDITPROPERTYVALUE                  0x200E3
#define HIDD_REVISIONRANGE                      0x200E4
#define HIDD_SETTINGSHOOKCONFIG                 0x200EC
#define HIDD_EXPORT                             0x200EE
#define HIDD_REVGRAPHFILTER                     0x200EF
#define HIDD_DELUNVERSIONED                     0x200F0
#define HIDD_INPUTLOGDLG                        0x200F1
#define HIDD_UNLOCK                             0x200F2
#define HIDD_CREATECHANGELIST                   0x200F3
#define HIDD_SETTINGSTBLAME                     0x200F4
#define HIDD_CONFLICTRESOLVE                    0x2010C
#define HIDD_MERGEALL                           0x20115
#define HIDD_MERGEWIZARD_REVRANGE               0x20116
#define HIDD_URLDIFF                            0x20117
#define HIDD_GOOFFLINE                          0x20118
#define HIDD_SETTINGSLOGCACHE                   0x20119
#define HIDD_LOGCACHESTATISTICS                 0x2011A
#define HIDD_SETTINGSBUGTRAQ                    0x2011B
#define HIDD_SETTINGSBUGTRAQADV                 0x2011C
#define HIDD_SETTINGSLOGCACHELIST               0x20127
#define HIDD_SETTINGSREVGRAPH                   0x20128
#define HIDD_SETTINGSREVGRAPHCOLORS             0x2012B
#define HIDD_AUTOTEXTTESTDLG                    0x20132
#define HIDD_SETTINGS_CONFIG                    0x20133
#define HIDD_SETTINGSOVERLAYHANDLERS            0x20134
#define HIDD_EDITPROPEXECUTABLE                 0x20138
#define HIDD_EDITPROPNEEDSLOCK                  0x20139
#define HIDD_EDITPROPMIMETYPE                   0x2013A
#define HIDD_EDITPROPBUGTRAQ                    0x2013B
#define HIDD_EDITPROPEOL                        0x2013C
#define HIDD_EDITPROPKEYWORDS                   0x2013D
#define HIDD_EDITPROPEXTERNALS                  0x2013E
#define HIDD_EDITPROPEXTERNALSVALUE             0x2013F
#define HIDD_EDITPROPTSVNSIZES                  0x20140
#define HIDD_EDITPROPTSVNLANG                   0x20141
#define HIDD_REPOCREATEFINISHED                 0x20144
#define HIDD_DIFFOPTIONS                        0x20145
#define HIDD_BUGTRAQREGEXTESTER                 0x20147
#define HIDD_CLEANUP                            0x20149
#define HIDD_SETTINGSDIALOGS3                   0x2014C
#define HIDD_RECYCLEBIN                         0x2014D
#define HIDD_EDITPROPLOCALHOOKS                 0x2014E
#define HIDD_EDITPROPUSERBOOL                   0x20150
#define HIDD_EDITPROPUSERSTATE                  0x20151
#define HIDD_EDITPROPUSERSINGLELINE             0x20152
#define HIDD_EDITPROPUSERMULTILINE              0x20153
#define HIDD_EDITPROPMERGELOGTEMPLATE           0x20159
#define HIDD_PLEASEWAIT                         0x2015B
#define HIDD_SETTINGS_CLEARAUTH                 0x2015C
#define HIDD_COLLABORATORSETTINGS               0x2015E
#define HIDD_MONITORPROJECT                     0x20167
#define HIDD_MONITOROPTIONS                     0x2016E
#define HIDD_SETTINGSSYNC                       0x20170
#define HIDD_PASSWORD                           0x20172
#define HIDD_SETTINGSUDIFF                      0x20173
