<?php
$countries = array(
"bg" => array("0","bg","Bulgarian","Milen A. Radev"),
"bs_BA" => array("0","bs_BA","Bosnian/Herzegovinan","Boris Musa"),
"cs" => array("0","cs","Czech","Radek Svarz"),
"da" => array("0","da","Danish","Jan Normann Nielsen, Gunther Strube"),
"de" => array("0","de","German","Stefan Küng, Lübbe Onken"),
"es" => array("0","es","Spanish","Fernando P. Nájera Cano, Antonio Romero Lopez"),
"fr" => array("0","fr","French","Olivier Booklage, Philippe Torche, Jean-Christophe Gigogne"),
"fi" => array("0","fi","Finnish","Pekka Järvinen"),
"hr" => array("0","hr","Croatian","Dinko Srkoc"),
"hu" => array("0","hu","Hungarian","Szente-Varga Bálint"),
"it" => array("0","it","Italian","Luca Berti"),
"ja" => array("0","ja","Japanese","Daisuke Deguchi (GUI), Kurasawa Nozomu (docs)"),
"ko" => array("0","ko","Korean","Hojin Choi, Jae-Hong Lee"),
"ka" => array("0","ka","Georgian","Gia Shervashidze"),
"nb" => array("0","nb","Norwegian, bokmål","Jostein Andersen"),
"nl" => array("0","nl","Dutch","Jean-Marc van Leerdam, Yves Reynhout"),
"pl" => array("0","pl","Polish","Michal Mielniczuk, Andrzej Rusin, Piotr Kontek"),
"pt_BR" => array("0","pt_BR","Portuguese, Brazil","Humberto Osório, Guilherme Cantisano, Juliano Ravasi Ferraz"),
"ru" => array("0","ru","Russian","Dzmitry Lazerka, Dimitry Mardiyan, Shura Zam, Alexander Leschinsky, Stanislav Petrakov"),
"sl" => array("0","sl","Slovenian","Goran Kavrecic, Martin Srebotnjak"),
"sv" => array("0","sv","Swedish","Johan Stenqvist, Johan Appelgren"),
"zh_CN" => array("0","zh_CN","Chinese, simplified","Cecil Sheng, Ken Chew, Cobra Net, Xingyu Wang, Lixinfeng"),
"zh_TW" => array("0","zh_TW","Chinese, traditional","Cecil Sheng"),
"zzz" => array("1","gb","Empty Catalog","")
);
?>
