//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by win_res.rc
//

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif

#define IDD_LOGIN                       101
#define IDC_LOGIN_PASSWORD              1000
#define IDC_LOGIN_PROMPT                1001
