<?php
$country = array(
"Tortoise_bg" => array("bg","Bulgarian"),
"Tortoise_bs_BA" => array("bs_BA","Bosnian/Herzegovinan"),
"Tortoise_cs" => array("cs","Czech"),
"Tortoise_da" => array("da","Danish"),
"Tortoise_de" => array("de","German"),
"Tortoise_es" => array("es","Spanish"),
"Tortoise_fr" => array("fr","French"),
"Tortoise_fi" => array("fi","Finnish"),
"Tortoise_hr" => array("hr","Croatian"),
"Tortoise_hu" => array("hu","Hungarian"),
"Tortoise_it" => array("it","Italian"),
"Tortoise_ja" => array("ja","Japanese"),
"Tortoise_ko" => array("ko","Korean"),
"Tortoise_ka" => array("ka","Georgian"),
"Tortoise_nb" => array("nb","Norwegian, bokmål"),
"Tortoise_nl" => array("nl","Dutch"),
"Tortoise_pl" => array("pl","Polish"),
"Tortoise_pt_BR" => array("pt_BR","Portuguese, Brazil"),
"Tortoise_ru" => array("ru","Russian"),
"Tortoise_sl" => array("sl","Slovenian"),
"Tortoise_sv" => array("sv","Swedish"),
"Tortoise_zh_CN" => array("zh_CN","Chinese, simplified"),
"Tortoise_zh_TW" => array("zh_TW","Chinese, traditional"),
"Tortoise.pot" => array("","Empty Catalog")
);
?>
