<?php
//
// TortoiseSVN variables for the Drupal status pages
//
// Copyright (C) 2004-2010 the TortoiseSVN team
// This file is distributed under the same license as TortoiseSVN
//
// $Author$
// $Date$
// $Rev$
//
// Author: Lübbe Onken 2004-2008
//         Stefan Küng 2004-2010
//

// 'Constants' that do not change upon a release
$tsvn_var['sf_project']="138498";
$tsvn_var['url1']="http://downloads.sourceforge.net/tortoisesvn/";
$tsvn_var['url2']="?download";
$tsvn_var['repos_base']="http://tortoisesvn.tigris.org/svn/tortoisesvn/";
$tsvn_var['flagpath']="/flags/world.small/";

// Variables that change upon each release
$tsvn_var['release']="1.6.8";
$tsvn_var['build']="19260";
$tsvn_var['svnver']="1.6.11";

$tsvn_var['repos_trunk']=$tsvn_var['repos_base'].'trunk/';
$tsvn_var['repos_branch']=$tsvn_var['repos_base'].'branches/1.6.x/';
?>
