//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDR_DLLMANIFEST                 2
#define IDI_ICON5                       105
#define IDI_MENU                        105
#define IDD_PROPPAGE                    107
#define IDI_APP                         108
#define IDS_MENUCHECKOUT                120
#define IDI_CHECKOUT                    121
#define IDS_MENUUPDATE                  121
#define IDS_MENUCOMMIT                  122
#define IDI_UPDATE                      122
#define IDS_MENUCREATEREPOS             123
#define IDI_COMMIT                      123
#define IDS_MENUADD                     124
#define IDI_ADD                         124
#define IDS_MENUREVERT                  125
#define IDI_REVERT                      125
#define IDS_MENUCLEANUP                 126
#define IDI_CLEANUP                     126
#define IDS_MENURESOLVE                 127
#define IDI_RESOLVE                     127
#define IDS_MENUSWITCH                  128
#define IDI_SWITCH                      128
#define IDS_MENUMERGE                   129
#define IDI_MERGE                       129
#define IDS_MENUBRANCH                  130
#define IDI_IMPORT                      130
#define IDS_MENUIMPORT                  131
#define IDI_EXPORT                      131
#define IDS_MENUEXPORT                  132
#define IDI_COPY                        132
#define IDS_MENUSETTINGS                133
#define IDI_DELETE                      133
#define IDS_MENUABOUT                   134
#define IDI_RENAME                      134
#define IDS_MENUSUBMENU                 135
#define IDI_DIFF                        135
#define IDS_MENUDESCCHECKOUT            136
#define IDI_LOG                         136
#define IDS_MENUDESCUPDATE              137
#define IDI_ABOUT                       137
#define IDS_MENUDESCCOMMIT              138
#define IDI_SETTINGS                    138
#define IDS_MENUDESCADD                 139
#define IDI_ICON1                       139
#define IDI_CREATEREPOS                 139
#define IDS_MENUDESCREVERT              140
#define IDI_ICON2                       140
#define IDI_CONFLICT                    140
#define IDS_MENUDESCCLEANUP             141
#define IDI_ICON3                       141
#define IDI_RELOCATE                    141
#define IDS_MENUDESCRESOLVE             142
#define IDI_HELP                        142
#define IDS_MENUDESCSWITCH              143
#define IDI_SHOWCHANGED                 143
#define IDS_MENUDESCIMPORT              144
#define IDI_IGNORE                      144
#define IDS_MENUDESCEXPORT              145
#define IDS_MENUDESCABOUT               146
#define IDS_MENUDESCCREATEREPOS         147
#define IDS_MENUDESCCOPY                148
#define IDS_MENUDESCMERGE               149
#define IDS_MENUDESCSETTINGS            150
#define IDS_MENUDESCDEFAULT             151
#define IDS_STATUSNONE                  152
#define IDS_STATUSUNVERSIONED           153
#define IDS_STATUSNORMAL                154
#define IDS_STATUSADDED                 155
#define IDS_STATUSABSENT                156
#define IDS_STATUSDELETED               157
#define IDS_STATUSREPLACED              158
#define IDS_STATUSMODIFIED              159
#define IDS_STATUSMERGED                160
#define IDS_STATUSCONFLICTED            161
#define IDS_STATUSOBSTRUCTED            162
#define IDS_PROPLOCKED                  163
#define IDS_PROPPROPERTY                164
#define IDS_PROPVALUE                   165
#define IDS_MENURENAME                  166
#define IDS_MENUDESCRENAME              167
#define IDS_MENUREMOVE                  168
#define IDS_MENUDESCREMOVE              169
#define IDS_MENUUPDATEEXT               170
#define IDS_MENUDESCUPDATEEXT           171
#define IDS_COLTITLESTATUS              172
#define IDS_COLDESCSTATUS               173
#define IDS_COLTITLEREV                 174
#define IDS_COLDESCREV                  175
#define IDS_MENUDIFF                    176
#define IDS_MENUDESCDIFF                177
#define IDS_DROPCOPYADDMENU             178
#define IDS_DROPMOVEMENU                179
#define IDS_MENULOG                     180
#define IDS_MENUDESCLOG                 181
#define IDS_COLTITLEURL                 182
#define IDS_COLDESCURL                  183
#define IDS_COLTITLESHORTURL            184
#define IDS_COLDESCSHORTURL             185
#define IDS_MENUCONFLICT                186
#define IDS_MENUDESCCONFLICT            187
#define IDS_MENURELOCATE                188
#define IDS_MENUDESCRELOCATE            189
#define IDS_MENUHELP                    190
#define IDS_MENUDESCHELP                191
#define IDS_MENUSHOWCHANGED             192
#define IDS_MENUDESCSHOWCHANGED         193
#define IDS_MENUIGNORE                  194
#define IDS_MENUDESCIGNORE              195
#define IDS_STATUSINCOMPLETE            196
#define IDS_STATUSIGNORED               197
#define IDS_DROPCOPYMENU                198
#define IDS_PROPWAITCANCEL              199
#define IDS_SETPROPTITLE                200
#define IDS_STATUSEXTERNAL              204
#define IDC_REVISION                    1001
#define IDC_LOCKED                      1002
#define IDC_REPOURL                     1003
#define IDC_CREVISION                   1004
#define IDC_CDATE                       1005
#define IDC_AUTHOR                      1006
#define IDC_TEXTSTATUS                  1007
#define IDC_TEXTDATE                    1008
#define IDC_PROPSTATUS                  1009
#define IDC_PROPDATE                    1010
#define IDC_PROPLIST                    1011
#define IDC_ADDBUTTON                   1012
#define IDC_REMOVEBUTTON                1013
#define IDC_EDITNAME                    1014
#define IDC_EDITVALUE                   1015
#define IDC_SHOWLOG                     1016
#define IDC_EDIT1                       1017
#define IDC_REPOURL2                    1017
#define IDC_CHECK1                      1018
#define IDC_RECURSIVE                   1018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5145
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         11019
#define _APS_NEXT_SYMED_VALUE           5101
#endif
#endif
