//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\Development\SVN\TortoiseSVN\src\Resources\TortoiseProcENG.rc
//
#define IDR_MAINFRAME                   1
#define IDD_SETTINGSPROXY               102
#define IDD_SETTINGSOVERLAY             106
#define IDD_SETTINGSSAVEDDATA           108
#define IDD_ABOUT                       129
#define IDD_LOGMESSAGE                  130
#define IDD_PROMPT                      131
#define IDD_CHECKOUT                    133
#define IDD_SVNPROGRESS                 134
#define IDD_LOGPROMPT                   135
#define IDD_IMPORT                      139
#define IDD_SWITCH                      140
#define IDD_MERGE                       141
#define IDD_COPY                        142
#define IDD_SETTINGSMAIN                143
#define IDR_ANIMATION                   148
#define IDR_MOVEANI                     149
#define IDD_RENAME                      151
#define IDD_UPDATE                      152
#define IDD_REPOSITORY_BROWSER          153
#define IDD_ADD                         155
#define IDD_RELOCATE                    157
#define IDD_CHANGEDFILES                158
#define IDD_SIMPLEPROMPT                160
#define IDD_INPUTDLG                    161
#define IDD_BLAME                       162
#define IDR_SEARCH                      163
#define IDI_DRIVES                      164
#define IDD_URL                         164
#define IDI_SSH                         165
#define IDI_PROXY                       166
#define IDI_MISC                        167
#define IDB_LOGOFLIPPED                 168
#define IDB_TTF_BMP                     169
#define IDD_SETTINGSPROGSADV            170
#define IDD_TOOLASSOC                   171
#define IDD_REVISION                    173
#define IDD_CHECKFORUPDATES             174
#define IDD_REVERT                      175
#define IDD_PROPERTIES                  177
#define IDD_REPOCREATE                  178
#define IDD_STATGRAPH                   179
#define IDD_PATCH_FILE_OPEN_CUSTOM      180
#define IDD_REVISIONGRAPH               182
#define IDR_REVISIONGRAPH               183
#define IDD_OVERLAYICONS                184
#define IDD_SETOVERLAYICONS             184
#define IDR_ACC_REVISIONGRAPH           185
#define IDI_SET_OVERLAYS                190
#define IDD_LOCK                        191
#define IDD_SETTINGSPROGSDIFF           192
#define IDD_SETTINGSPROGSMERGE          193
#define IDD_SETTINGSPROGSUNIDIFF        194
#define IDD_SETTINGSLOOKANDFEEL         195
#define IDI_GENERAL                     195
#define IDD_SETTINGSDIALOGS             196
#define IDI_LOOKANDFEEL                 196
#define IDI_ICONSET                     197
#define IDI_DIALOGS                     198
#define IDD_DIFFFILES                   199
#define IDB_CANCELHIGHLIGHT             201
#define IDB_CANCELNORMAL                202
#define IDB_BITMAP1                     203
#define IDB_CANCELPRESSED               203
#define IDB_LOGFILTER                   204
#define IDD_RESOLVE                     207
#define IDD_CREATEPATCH                 208
#define IDI_WARNING_GENERAL             210
#define IDD_HISTORYDLG                  211
#define IDR_CLEANUPANI                  212
#define IDD_SETTINGSCOLORS              212
#define IDI_ACTIONADDED                 213
#define IDD_SETTINGSMISC                213
#define IDI_ACTIONDELETED               214
#define IDI_ACTIONMODIFIED              215
#define IDI_ACTIONREPLACED              216
#define IDI_REVGRAPH_ADDED              217
#define IDI_REVGRAPH_ADDEDPLUS          218
#define IDI_REVGRAPH_DELETED            219
#define IDI_REVGRAPH_LASTCOMMIT         220
#define IDI_REVGRAPH_RENAMED            221
#define IDI_REVGRAPH_REPLACED           222
#define IDR_REVGRAPHBAR                 223
#define IDI_SAVEDDATA                   225
#define IDD_EDITPROPERTIES              226
#define IDD_EDITPROPERTYVALUE           227
#define IDD_REVISIONRANGE               228
#define IDI_GRAPHBAR                    229
#define IDI_GRAPHBARSTACKED             230
#define IDI_GRAPHLINE                   231
#define IDI_GRAPHLINESTACKED            232
#define IDI_GRAPHPIE                    233
#define IDI_SWITCHLEFTRIGHT             234
#define IDS_CHSTAT_FILECOL              1000
#define IDS_CHSTAT_WCCOL                1001
#define IDS_CHSTAT_REPOCOL              1002
#define IDC_LOGLIST                     1003
#define IDC_PASSEDIT                    1004
#define IDC_INFOTEXT                    1005
#define IDC_CHECKOUTDIRECTORY           1010
#define IDC_SVNPROGRESS                 1013
#define IDC_LOGMESSAGE                  1014
#define IDC_LOGMSG                      1015
#define IDC_TOURL                       1015
#define IDC_EXTDIFF                     1015
#define IDC_EXTMERGE                    1016
#define IDC_MESSAGE                     1017
#define IDC_DIFFVIEWER                  1017
#define IDC_NEWEST                      1019
#define IDC_EXTDIFFBROWSE               1021
#define IDC_EXTMERGEBROWSE              1022
#define IDC_CHANGEDDIRS                 1023
#define IDC_ENABLE                      1023
#define IDC_SAVECHECK                   1023
#define IDC_NAME                        1027
#define IDC_REVNUM                      1027
#define IDC_SERVERADDRESS               1027
#define IDC_TEMPEXTENSIONS              1027
#define IDC_REVISON_START               1027
#define IDC_USEREDIT                    1027
#define IDC_REVNUM2                     1028
#define IDC_URLCOMBO                    1029
#define IDC_FONTNAMES                   1030
#define IDC_LOGBUTTON                   1031
#define IDC_FINDBRANCHSTART             1031
#define IDC_GETALL                      1031
#define IDC_EDITCONFIG                  1031
#define IDC_UPDATE                      1031
#define IDC_REVISION_HEAD               1032
#define IDC_REVISION_N                  1033
#define IDC_REVISION_NUM                1034
#define IDC_FINDBRANCHEND               1034
#define IDC_NEWEST2                     1034
#define IDC_REVISION_N2                 1035
#define IDC_BROWSE                      1035
#define IDC_BROWSE2                     1036
#define IDC_CHECKOUTDIRECTORY_BROWSE    1036
#define IDC_INCLUDEPATHS                1036
#define IDC_REPOS_TREE                  1037
#define IDC_SERVERPORT                  1038
#define IDC_USERNAME                    1039
#define IDC_PASSWORD                    1040
#define IDC_TIMEOUT                     1041
#define IDC_FILELIST                    1043
#define IDC_ADDLIST                     1043
#define IDC_CHANGEDLIST                 1043
#define IDC_MENULIST                    1043
#define IDC_REVERTLIST                  1043
#define IDC_PROPERTYLIST                1043
#define IDC_LANGUAGECOMBO               1044
#define IDC_FROMURL                     1045
#define IDC_COMMIT_TO                   1046
#define IDC_REMOVABLE                   1048
#define IDC_NETWORK                     1049
#define IDC_FIXED                       1050
#define IDC_CDROM                       1051
#define IDC_HINTLABEL                   1052
#define IDC_REVISION_END                1053
#define IDC_VERSIONABOUT                1054
#define IDC_STATIC1                     1055
#define IDC_STATIC2                     1056
#define IDC_STATIC4                     1058
#define IDC_CLEARAUTH                   1059
#define IDC_UNKNOWN                     1061
#define IDC_INPUTTEXT                   1064
#define IDC_HINTTEXT                    1065
#define IDC_SELECTALL                   1067
#define IDC_SSHCLIENT                   1068
#define IDC_SSHBROWSE                   1069
#define IDC_REPOS_BAR_CNR               1070
#define IDC_DEFAULTLOG                  1071
#define IDC_DONTCONVERT                 1073
#define IDC_RAM                         1073
#define IDC_NON_RECURSIVE               1073
#define IDC_CHECKNEWERVERSION           1073
#define IDC_SHOWUNVERSIONED             1073
#define IDC_USEFROMURL                  1073
#define IDC_EXPORT_CHECKOUTDIR          1074
#define IDC_VERSIONBOX                  1075
#define IDC_LABEL                       1076
#define IDC_MSGVIEW                     1077
#define IDC_EXCEPTIONS                  1077
#define IDC_BUGID                       1077
#define IDC_WCURL                       1077
#define IDC_EXCLUDEPATHS                1077
#define IDC_WCPATH                      1078
#define IDC_DRIVEGROUP                  1079
#define IDC_PROXYGROUP                  1080
#define IDC_SSHGROUP                    1081
#define IDC_MISCGROUP                   1082
#define IDC_COMMITGROUP                 1083
#define IDC_WEBLINK                     1084
#define IDC_SUPPORTLINK                 1085
#define IDC_FONTSIZES                   1086
#define IDC_COMMITFILETIMES             1088
#define IDC_ONLYEXPLORER                1088
#define IDC_DIFFVIEWERBROWSE            1089
#define IDC_EXTDIFFADVANCED             1090
#define IDC_EXTDIFF_OFF                 1091
#define IDC_EXTDIFF_ON                  1092
#define IDC_EXTMERGEADVANCED            1093
#define IDC_EXTMERGE_OFF                1094
#define IDC_EXTMERGE_ON                 1095
#define IDC_DIFFVIEWER_OFF              1096
#define IDC_DIFFVIEWER_ON               1097
#define IDC_ADDTOOL                     1098
#define IDC_EDITTOOL                    1099
#define IDC_REMOVETOOL                  1100
#define IDS_AUTH_USERNAME               1100
#define IDS_AUTH_PASSWORD               1101
#define IDC_TOOLLISTCTRL                1101
#define IDC_EXTEDIT                     1102
#define IDC_TOOLEDIT                    1103
#define IDC_TOOLBROWSE                  1104
#define IDC_SHORTDATEFORMAT             1105
#define IDC_SUMMARYTEXT                 1106
#define IDC_STATISTICS                  1108
#define IDC_URLCOMBO2                   1109
#define IDC_COMMITLABEL                 1110
#define IDS_REG_ERROR                   1110
#define IDC_PROGRESS                    1111
#define IDC_YOURVERSION                 1112
#define IDC_CURRENTVERSION              1113
#define IDC_CHECKRESULT                 1114
#define IDC_REVISION_HEAD1              1115
#define IDC_REVISION_N1                 1116
#define IDC_REVISION_START              1118
#define IDC_BUGIDLABEL                  1119
#define IDC_OLDLOGS                     1124
#define IDC_ICONSETCOMBO                1124
#define IDC_CHIST                       1125
#define IDC_CHECK1                      1126
#define IDC_F5HINT                      1127
#define IDC_RADIOBDB                    1128
#define IDC_RADIOFSFS                   1129
#define IDC_CHECK_STOPONCOPY            1130
#define IDC_GRAPH                       1131
#define IDC_STATBUTTON                  1132
#define IDC_PATCH_TO_CLIPBOARD          1132
#define IDC_CHECKREPO                   1132
#define IDC_SELECTOVERLAYSET            1132
#define IDC_WCLOG                       1132
#define IDC_LOG                         1132
#define IDC_GRAPHCOMBO                  1133
#define IDC_GRAPHTYPELABEL              1134
#define IDC_COMMITSEACHWEEK             1135
#define IDC_MOSTACTIVEAUTHOR            1136
#define IDC_LEASTACTIVEAUTHOR           1137
#define IDC_FILECHANGESEACHWEEK         1138
#define IDC_COMMITSEACHWEEKAVG          1140
#define IDC_COMMITSEACHWEEKMIN          1141
#define IDC_COMMITSEACHWEEKMAX          1142
#define IDC_MOSTACTIVEAUTHORAVG         1143
#define IDC_MOSTACTIVEAUTHORMIN         1144
#define IDC_MOSTACTIVEAUTHORMAX         1145
#define IDC_LEASTACTIVEAUTHORAVG        1146
#define IDC_LEASTACTIVEAUTHORMIN        1147
#define IDC_LEASTACTIVEAUTHORMAX        1148
#define IDC_FILECHANGESEACHWEEKAVG      1149
#define IDC_FILECHANGESEACHWEEKMIN      1150
#define IDC_FILECHANGESEACHWEEKMAX      1151
#define IDS_MSGBOX_DONOTSHOWAGAIN       1153
#define IDS_MSGBOX_ABORT                1154
#define IDS_MSGBOX_RETRY                1155
#define IDC_MOSTACTIVEAUTHORNAME        1155
#define IDS_MSGBOX_IGNORE               1156
#define IDC_LEASTACTIVEAUTHORNAME       1156
#define IDS_MSGBOX_CANCEL               1157
#define IDC_AVG                         1157
#define IDS_MSGBOX_TRYAGAIN             1158
#define IDC_MIN                         1158
#define IDS_MSGBOX_CONTINUE             1159
#define IDC_MAX                         1159
#define IDS_MSGBOX_OK                   1160
#define IDC_NUMWEEK                     1160
#define IDS_MSGBOX_YES                  1161
#define IDC_NUMAUTHOR                   1161
#define IDS_MSGBOX_NO                   1162
#define IDC_NUMCOMMITS                  1162
#define IDS_SVNACTION_ADD               1163
#define IDC_NUMFILECHANGES              1163
#define IDS_SVNACTION_COPY              1164
#define IDC_NUMWEEKVALUE                1164
#define IDS_SVNACTION_DELETE            1165
#define IDC_NUMAUTHORVALUE              1165
#define IDS_SVNACTION_RESTORE           1166
#define IDC_NUMCOMMITSVALUE             1166
#define IDS_SVNACTION_REVERT            1167
#define IDC_NUMFILECHANGESVALUE         1167
#define IDS_SVNACTION_RESOLVE           1168
#define IDS_SVNACTION_UPDATE            1169
#define IDC_SHOWFOLDERSTATUS            1169
#define IDS_SVNACTION_COMPLETED         1170
#define IDC_ICONSETLABEL                1170
#define IDS_SVNACTION_EXTERNAL          1171
#define IDC_ICONLIST                    1171
#define IDS_SVNACTION_MODIFIED          1172
#define IDC_LISTRADIO                   1172
#define IDS_SVNACTION_REPLACED          1173
#define IDC_SYMBOLRADIO                 1173
#define IDS_SVNACTION_POSTFIX           1174
#define IDS_SVNACTION_FAILEDREVERT      1175
#define IDS_SVNACTION_STATUS            1176
#define IDS_SVNACTION_SKIP              1177
#define IDS_PROGS_EXTCOL                1178
#define IDS_PROGS_TOOLCOL               1179
#define IDC_DRYRUNBUTTON                1179
#define IDS_LOG_FILE                    1180
#define IDC_DIFFBUTTON                  1180
#define IDS_SVN_USERCANCELLED           1181
#define IDC_AUTOCLOSECOMBO              1181
#define IDS_LOG_SIZE                    1182
#define IDC_COPYHEAD                    1182
#define IDC_COPYWC                      1183
#define IDC_AUTOCOMPLETION              1184
#define IDC_COPYREV                     1185
#define IDC_COPYREVTEXT                 1186
#define IDC_BROWSEFROM                  1187
#define IDS_REPO_BROWSEREV              1190
#define IDS_REPO_BROWSEURL              1191
#define IDC_SPLITTERTOP                 1191
#define IDC_SPLITTERBOTTOM              1192
#define IDC_SEARCHEDIT                  1194
#define IDC_FILTERICON                  1196
#define IDC_DATETO                      1198
#define IDC_DATEFROM                    1199
#define IDS_SSL_CERTIFICATETYPE         1200
#define IDC_FROMLABEL                   1200
#define IDS_SSL_ACCEPTQUESTION          1201
#define IDC_TOLABEL                     1201
#define IDS_SSL_CLIENTCERTIFICATEFILENAME 1202
#define IDC_NOEXTERNALS                 1202
#define IDS_SSL_PEM                     1203
#define IDC_KEEPLOCK                    1203
#define IDS_SSL_PKCS12                  1204
#define IDS_IMPORT_DEFAULTMSG           1205
#define IDS_LOG_COPYFROM                1206
#define IDS_LOG_MESSAGE                 1207
#define IDC_CHECKBOX                    1207
#define IDS_LOG_REVISION                1208
#define IDC_NEXTHUNDRED                 1208
#define IDS_LOG_AUTHOR                  1209
#define IDC_SHOWUNMODIFIED              1209
#define IDS_LOG_DATE                    1210
#define IDS_LOG_REVERT_CONFIRM          1211
#define IDC_STEALLOCKS                  1211
#define IDS_LOG_POPUP_COMPARE           1212
#define IDC_LOCKMESSAGE                 1212
#define IDS_LOG_POPUP_SAVE              1213
#define IDC_LOCKTITLELABEL              1213
#define IDS_LOG_POPUP_COMPARETWO        1214
#define IDC_OLDAPILOGS                  1214
#define IDS_LOG_POPUP_UPDATE            1215
#define IDC_CHECKNEWERBUTTON            1215
#define IDS_LOG_POPUP_COPY              1216
#define IDS_LOGPROMPT_FILE              1217
#define IDC_SIMPLECONTEXT               1217
#define IDS_LOGPROMPT_STATUS            1218
#define IDC_FILTERCANCEL                1218
#define IDS_LOGPROMPT_ASKADD            1219
#define IDS_LOGPROMPT_NOTHINGTOCOMMIT   1220
#define IDC_REALM                       1220
#define IDS_PROGRS_ATREV                1221
#define IDC_AUTOCOMPLETIONTIMEOUT       1221
#define IDS_PROGRS_ACTION               1222
#define IDC_AUTOCOMPLETIONTIMEOUTLABEL  1222
#define IDS_PROGRS_PATH                 1223
#define IDC_RECURSIVECHECK              1223
#define IDS_PROGRS_TITLEFIN             1224
#define IDC_SPELL                       1224
#define IDS_PROGRS_TITLE_CHECKOUT       1225
#define IDS_PROGRS_TITLE_IMPORT         1226
#define IDC_WCPATHLABEL                 1226
#define IDS_PROGRS_TITLE_UPDATE         1227
#define IDC_REPOCHECK                   1227
#define IDS_PROGRS_TITLE_COMMIT         1228
#define IDC_SHOW_LOG                    1228
#define IDS_PROGRS_TITLE_ADD            1229
#define IDC_HIDEPATHS                   1229
#define IDS_PROGRS_TITLE_REVERT         1230
#define IDC_WCURLFROM                   1230
#define IDS_PROGRS_TITLE_RESOLVE        1231
#define IDC_RESOLVELIST                 1231
#define IDS_PROGRS_TITLE_SWITCH         1232
#define IDC_DOSWITCH                    1232
#define IDS_PROGRS_TITLE_EXPORT         1233
#define IDS_PROGRS_TITLE_MERGE          1234
#define IDS_PROGRS_TITLE_COPY           1235
#define IDC_PATCHLIST                   1235
#define IDS_PROGRS_MIMETYPE             1236
#define IDC_EDITSERVERS                 1237
#define IDS_PROGRS_COPY_WARNING         1238
#define IDC_EXTERNALWARNING             1238
#define IDS_PROGRS_COMMITT_TRUNK        1239
#define IDC_SOUNDS                      1239
#define IDS_PROGRS_REVERTMARKERS        1240
#define IDC_ENABLEACCELERATORS          1240
#define IDS_SETTINGS_SELECTDIFF         1241
#define IDC_MESSAGEGROUP                1241
#define IDS_SETTINGS_SELECTDIFFVIEWER   1242
#define IDC_LISTGROUP                   1242
#define IDS_SETTINGS_SELECTMERGE        1243
#define IDC_PROGRESSBAR                 1243
#define IDS_SETTINGS_SELECTSSH          1244
#define IDC_PROGRESSLABEL               1244
#define IDS_SETTINGS_EXTDIFF_TT         1245
#define IDC_HISTORYLIST                 1245
#define IDS_SETTINGS_EXTDIFFBROWSE_TT   1246
#define IDC_HISTORY                     1246
#define IDS_SETTINGS_CHANGEDDIRS_TT     1247
#define IDS_SETTINGS_TEMPEXTENSIONS_TT  1248
#define IDS_SETTINGS_FOLDERSTATUS_TT    1249
#define IDC_CONFLICTCOLOR               1249
#define IDS_SETTINGS_EXTMERGE_TT        1250
#define IDC_ADDEDCOLOR                  1250
#define IDS_SETTINGS_PROXYSERVER_TT     1251
#define IDC_DELETEDCOLOR                1251
#define IDS_SETTINGS_DIFFVIEWER_TT      1252
#define IDC_MERGEDCOLOR                 1252
#define IDS_SETTINGS_AUTOCLOSE_TT       1253
#define IDC_MODIFIEDCOLOR               1253
#define IDS_UTILS_SELECTTEXTVIEWER      1254
#define IDC_RESTORE                     1254
#define IDS_SETTINGS_CONVERTBASE_TT     1255
#define IDC_DELETEDNODECOLOR            1255
#define IDS_PROC_WARNREVERT             1256
#define IDC_ADDEDNODECOLOR              1256
#define IDS_PROC_CLEANUPFINISHED        1257
#define IDC_RENAMEDNODECOLOR            1257
#define IDS_PROC_REPOCREATEERR          1258
#define IDC_REPLACEDNODECOLOR           1258
#define IDS_PROC_EXPORT_1               1259
#define IDC_COPYSTARTLABEL              1259
#define IDS_PROC_EXPORT_2               1260
#define IDC_UNVERSIONEDRECURSE          1260
#define IDS_PROC_EXPORT_3               1261
#define IDC_SKIPPER                     1261
#define IDS_PROC_EXPORT_4               1262
#define IDC_SKIPPERLABEL                1262
#define IDS_PROC_COPY_SUCCESS           1263
#define IDC_STACKED                     1263
#define IDS_PROC_SETTINGS_TITLE         1264
#define IDC_SHOWIGNORED                 1264
#define IDC_IGNORECASE                  1265
#define IDS_PROC_OVERWRITE_CONFIRM      1266
#define IDC_IMPORTIGNORED               1266
#define IDS_PROC_REPOCREATEFINISHED     1267
#define IDC_IGNOREANCESTRY              1267
#define IDS_PROC_RELOCATEFINISHED       1268
#define IDC_MAXHISTORY                  1268
#define IDS_PROC_MOVING                 1269
#define IDC_CACHEDEFAULT                1269
#define IDS_PROC_RELOCATING             1270
#define IDC_CACHESHELL                  1270
#define IDS_APPNAME                     1271
#define IDC_CACHENONE                   1271
#define IDS_MSGBOX_DONOTSHOW            1272
#define IDC_URLHISTORY                  1272
#define IDS_PROC_COPYING                1273
#define IDC_URLHISTCLEAR                1273
#define IDS_PROC_COPYINGPROG            1274
#define IDC_LOGHISTORY                  1274
#define IDS_PROC_MOVINGPROG             1275
#define IDC_LOGHISTCLEAR                1275
#define IDS_PROC_CPYMVPROG2             1276
#define IDC_RESIZABLEHISTCLEAR          1276
#define IDS_PROC_ENTERURL               1277
#define IDC_RESIZABLEHISTORY            1277
#define IDC_AUTHHISTORY                 1278
#define IDS_SETTINGS_SHORTDATEFORMAT_TT 1279
#define IDC_BUTTON4                     1279
#define IDC_AUTHHISTCLEAR               1279
#define IDS_ERR_THREADSTARTFAILED       1281
#define IDC_EDITPROPLIST                1281
#define IDS_ERR_EXTDIFFSTART            1282
#define IDC_EDITPROPS                   1282
#define IDS_ERR_NOCOMMAND               1283
#define IDC_PROPPATH                    1283
#define IDS_ERR_NOCOMMANDVALUE          1284
#define IDS_ERR_NOSTATUS                1285
#define IDC_REMOVEPROPS                 1285
#define IDS_ERR_CLEANUP                 1286
#define IDS_ERR_NOURLOFFILE             1287
#define IDC_GROUP                       1287
#define IDS_ERR_WCCHANGED               1288
#define IDS_ERR_COPYFILES               1289
#define IDS_ERR_EXTMERGESTART           1290
#define IDC_PROPNAMECOMBO               1290
#define IDS_ERR_NOTUPTODATE             1291
#define IDC_PROPVALUE                   1291
#define IDS_ERR_FAILEDIGNOREPROPERTY    1292
#define IDC_PROPNAME                    1292
#define IDS_ERR_DIFFVIEWSTART           1293
#define IDC_PROPVALUEGROUP              1293
#define IDS_ERR_SSL_VALIDATE            1294
#define IDC_PROPRECURSIVE               1294
#define IDS_ERR_SSL_UNKNOWNCA           1295
#define IDS_ERR_SSL_CNMISMATCH          1296
#define IDC_ASPDOTNETHACK               1296
#define IDS_ERR_SSL_EXPIREDORNOTYETVALID 1297
#define IDC_GRAPHBARBUTTON              1297
#define IDS_SSL_ACCEPTALWAYS            1298
#define IDC_GRAPHBARSTACKEDBUTTON       1298
#define IDS_SSL_ACCEPTTEMP              1299
#define IDC_GRAPHLINEBUTTON             1299
#define IDS_SSL_REJECT                  1300
#define IDC_GRAPHLINESTACKEDBUTTON      1300
#define IDC_SORTNUMERICAL               1300
#define IDS_ERR_SSL_NOTYETVALID         1301
#define IDC_GRAPHPIEBUTTON              1301
#define IDC_FIRSTURL                    1301
#define IDS_ERR_SSL_EXPIRED             1302
#define IDC_DIFFSTATIC1                 1302
#define IDS_ERR_COPYITSELF              1303
#define IDC_SECONDURL                   1303
#define IDS_ERR_INVALIDREV              1304
#define IDC_DIFFSTATIC2                 1304
#define IDS_ERR_EMPTYDIFF               1305
#define IDC_URLLABEL                    1305
#define IDS_ERR_NOTHINGTOADD            1306
#define IDC_REVGROUP                    1306
#define IDS_ERR_ERROR                   1307
#define IDC_SWITCHLEFTRIGHT             1307
#define IDS_ERR_NOVALIDPATH             1308
#define IDC_SAVEPROP                    1308
#define IDS_ERR_FAILEDUNIGNOREPROPERTY  1309
#define IDC_LOADPROP                    1309
#define IDS_ERR_NOTHINGTOREVERT         1310
#define IDC_ADDPROPS                    1310
#define IDC_LOCKWARNING                 1311
#define IDS_ERR_NOCOMMONCOPYFROM        1311
#define IDS_ERR_GDIPLUS_MISSING         1312
#define IDS_ERR_NOTENOUGHMEMORY         1313
#define IDS_ERR_MUSTBEURL               1314
#define IDS_ERR_INVALIDREVNOWC          1315
#define IDS_ERR_MERGEIDENTICALREVISIONS 1316
#define IDS_WARN_FOLDERNOTEXIST         1400
#define IDS_WARN_SHAREFILEACCESS        1401
#define IDS_WARN_RELOCATEREALLY         1402
#define IDS_WARN_UPDATETOREV_WITHMODS   1403
#define IDS_WARN_FOLDERNOTEMPTY         1404
#define IDS_WARN_WARNING                1405
#define IDS_WARN_NOTE                   1406
#define IDS_WARN_NOVALIDPATH            1407
#define IDS_WARN_LOCKOUTDATED           1408
#define IDS_WARN_SVNNEEDSLOCK           1409
#define IDS_CHECKOUT_TT_DIR             1500
#define IDS_CHECKOUT_EXPORTDIR          1501
#define IDS_IMPORT_TT_MODULENAMECHECK   1510
#define IDS_IMPORT_TT_TEMPFILES         1511
#define IDS_PROC_RENAME                 1550
#define IDS_PROC_NEWNAME                1551
#define IDS_PROC_NEWNAMECOPY            1552
#define IDS_PROC_NEWNAMEMOVE            1553
#define IDS_PROC_NEWNAMELABEL           1554
#define IDS_PROC_MULTIRENAME            1560
#define IDS_REPOBROWSE_SAVEAS           1600
#define IDS_REPOBROWSE_SHOWLOG          1601
#define IDS_REPOBROWSE_OPEN             1602
#define IDS_REPOBROWSE_COPY             1603
#define IDS_REPOBROWSE_DELETE           1604
#define IDS_REPOBROWSE_IMPORT           1605
#define IDS_REPOBROWSE_RENAME           1606
#define IDS_REPOBROWSE_MKDIR            1607
#define IDS_REPOBROWSE_IMPORTFOLDER     1608
#define IDS_REPOBROWSE_REFRESH          1609
#define IDS_REPOBROWSE_SHOWPROP         1610
#define IDS_REPOBROWSE_COPYTOWC         1611
#define IDS_REPOBROWSE_URLTOCLIPBOARD   1612
#define IDS_REPOBROWSE_COPYERROR        1613
#define IDS_REPOBROWSE_SORTNUMERICAL    1614
#define IDS_REPOBROWSE_URLALREADYEXISTS 1630
#define IDS_REPOBROWSE_INVALIDDROPDATA  1631
#define IDS_REPOBROWSE_SAVEASPROGTITLE  1640
#define IDS_REPOBROWSE_SAVEAS_LINE1     1641
#define IDS_REPOBROWSE_SAVEAS_LINE2     1642
#define IDS_REPOBROWSE_COPYTOWCPROGTITLE 1643
#define IDS_REPOBROWSE_COPYTOWC_LINE1   1644
#define IDS_REPOBROWSE_COPYTOWC_LINE2   1645
#define IDS_REPOBROWSE_INITWAIT         1660
#define IDS_REPOBROWSE_MULTIIMPORT      1670
#define IDS_REPOBROWSE_MULTICOPY        1671
#define IDS_REPOBROWSE_MULTIMOVE        1672
#define IDS_ABOUTVERSION                1700
#define IDS_ABOUTVERSIONBOX             1701
#define IDS_DLGTITLE_ADD_DIFF_TOOL      1750
#define IDS_DLGTITLE_ADD_MERGE_TOOL     1751
#define IDS_DLGTITLE_EDIT_DIFF_TOOL     1752
#define IDS_DLGTITLE_EDIT_MERGE_TOOL    1753
#define IDS_DLGTITLE_ADV_DIFF           1754
#define IDS_DLGTITLE_ADV_MERGE          1755
#define IDS_LOG_POPUP_DIFF              1800
#define IDS_LOG_POPUP_REVERTREV         1801
#define IDS_LOG_POPUP_GNUDIFF           1802
#define IDS_LOG_POPUP_FIND              1803
#define IDS_LOG_POPUP_OPEN              1804
#define IDS_LOG_POPUP_EDITAUTHOR        1805
#define IDS_LOG_POPUP_EDITLOG           1806
#define IDS_LOG_POPUP_OPENWITH          1807
#define IDS_LOG_POPUP_REVERTREVS        1808
#define IDS_LOG_POPUP_COPYTOCLIPBOARD   1809
#define IDS_LOG_POPUP_REVERTTOREV       1810
#define IDS_LOG_POPUP_BLAMECOMPARE      1811
#define IDS_LOG_POPUP_BLAMEREVS         1812
#define IDS_LOG_POPUP_BLAMEDIFF         1813
#define IDS_LOG_COPY_SUCCESS            1830
#define IDS_LOG_MESSAGEEDITTITLE        1831
#define IDS_LOG_AUTHOREDITTITLE         1832
#define IDS_LOG_SHOWALL                 1833
#define IDS_LOG_SHOWRANGE               1834
#define IDS_LOG_BUGIDS                  1840
#define IDS_LOG_FILTER_ALL              1850
#define IDS_LOG_FILTER_PATHS            1851
#define IDS_LOG_FILTER_AUTHORS          1852
#define IDS_LOG_FILTER_MESSAGES         1853
#define IDS_LOG_FILTER_REVS             1854
#define IDS_LOG_ACTIONS                 1870
#define IDS_LOG_REVERTTOREV_CONFIRM     1890
#define IDS_PROGRESSGETFILE             1900
#define IDS_PROGRESSREVISION            1901
#define IDS_PROGRESSWAIT                1902
#define IDS_PROGRESS_UNIFIEDDIFF        1903
#define IDS_PROGRESS_COMPARE            1904
#define IDS_PROGRESS_INFO               1905
#define IDS_PROGRESSGETFILEREVISION     1906
#define IDS_PROGRESSIMPORT              1907
#define IDS_PROGRESSREVISIONTEXT        1908
#define IDS_INPUT_ENTERLOG              2000
#define IDS_INPUT_LOGTITLE              2001
#define IDS_INPUT_REMOVELOGMSG          2002
#define IDS_INPUT_ADDLOGMSG             2003
#define IDS_INPUT_COPYLOGMSG            2004
#define IDS_INPUT_MKDIRLOGMSG           2005
#define IDS_INPUT_MOVELOGMSG            2006
#define IDS_INPUT_ADDFOLDERLOGMSG       2007
#define IDS_INPUT_ADDFILEFOLDERMSG      2008
#define IDS_INPUT_RENAMELOGMSG          2009
#define IDS_BLAME_PROGRESSTITLE         2100
#define IDS_BLAME_PROGRESSINFO          2101
#define IDS_BLAME_PROGRESSCANCEL        2102
#define IDS_BLAME_PROGRESSINFO2         2103
#define IDS_BLAME_PROGRESSINFOSTART     2104
#define IDS_BLAME_PROGRESSLOGSTART      2105
#define IDS_MENUREFRESH                 2150
#define IDS_LOG_COMPAREWITHBASE         2200
#define IDS_LOG_BROWSEREPO              2201
#define IDS_PROC_ENTERURLLABEL          2300
#define IDS_PROC_PATCHTITLE             2301
#define IDS_PROC_SAVEPATCHTO            2302
#define IDS_PROC_REPOCREATESHAREWARN    2303
#define IDS_PROC_CLEANUP                2304
#define IDS_PROC_REMOVEFORCE            2305
#define IDS_PROC_YESTOALL               2306
#define IDS_PROC_IGNORESUCCESS          2307
#define IDS_PROC_RESOLVE                2308
#define IDS_PROC_RTFM                   2309
#define IDS_PROC_CASERENAME             2310
#define IDS_PROC_UnIGNORESUCCESS        2311
#define IDS_PROC_UNIGNORESUCCESS        2311
#define IDS_PROC_FORCEMOVE              2312
#define IDS_PROC_OMMITEXTERNALS         2313
#define IDS_PROC_ICONCACHEREBUILT       2314
#define IDS_PROC_ICONCACHENOTREBUILT    2315
#define IDS_PROC_EXPORTFOLDERNAME       2316
#define IDS_PROC_EXPORTFOLDERNAME2      2317
#define IDS_PROC_REMOVEFORCEFOLDER      2318
#define IDS_PROC_DIFFTITLE              2330
#define IDS_PROC_DIFFLABEL              2331
#define IDS_DIFF_WCNAME                 2400
#define IDS_DIFF_BASENAME               2401
#define IDS_DIFF_WORKINGCOPY            2402
#define IDS_DIFF_REVISIONPATCHED        2403
#define IDS_DIFF_REMOTENAME             2404
#define IDS_DIFF_WORKINGBASE            2405
#define IDS_COMMONFILEFILTER            2500
#define IDS_PROGRAMSFILEFILTER          2501
#define IDS_CERTIFICATESFILEFILTER      2502
#define IDS_PATCHFILEFILTER             2503
#define IDS_PICTUREFILEFILTER           2504
#define IDS_CHECKUPDATE_SUMMARY         2600
#define IDS_LOGPROMPT_EXTERNALS         2700
#define IDS_LOGPROMPT_STATISTICSFORMAT  2701
#define IDS_LOGPROMPT_ONLYNUMBERS       2702
#define IDS_LOGPROMPT_NOISSUEWARNING    2703
#define IDS_LOGPROMPT_NOTHINGTOCOMMITUNVERSIONED 2704
#define IDS_LOGPROMPT_HISTORY_TT        2705
#define IDS_LOGPROMPT_HISTORYHINT_TT    2706
#define IDS_LOGPROMPT_POPUP_PASTEFILELIST 2750
#define IDS_SPELLEDIT_THESAURUS         3000
#define IDS_SPELLEDIT_CORRECTIONS       3001
#define IDS_SPELLEDIT_NOCORRECTIONS     3002
#define IDS_SPELLEDIT_NOTHESAURUS       3003
#define IDS_SETTINGS_CHECKNEWER_TT      3100
#define IDS_SETTINGS_ONLYEXPLORER_TT    3101
#define IDS_SETTINGS_MENULAYOUT_TT      3102
#define IDS_SETTINGS_EXCLUDELIST_TT     3103
#define IDS_SETTINGS_INCLUDELIST_TT     3104
#define IDS_SETTINGS_CLEARAUTH_TT       3105
#define IDS_SETTINGS_COMMITFILETIMES_TT 3106
#define IDS_SETTINGS_ICONSETCHANGED     3108
#define IDS_SETTINGS_PROXYEXCEPTIONS_TT 3109
#define IDS_SETTINGS_READONLYNAME       3110
#define IDS_SETTINGS_LOCKEDNAME         3111
#define IDS_SETTINGS_OLDLOGAPIS_TT      3112
#define IDS_SETTINGS_SIMPLECONTEXT_TT   3113
#define IDS_SETTINGS_AUTOCOMPLETION_TT  3114
#define IDS_SETTINGS_AUTOCOMPLETIONTIMEOUT_TT 3115
#define IDS_SETTINGS_RECURSIVE_TT       3116
#define IDS_SETTINGS_USEWCURL_TT        3117
#define IDS_SETTINGS_SPELLCHECKER_TT    3118
#define IDS_SETTINGS_REPOCHECK_TT       3119
#define IDS_SETTINGS_OWNERDRAWN_TT      3120
#define IDS_SETTINGS_UNVERSIONEDRECURSE_TT 3121
#define IDS_SETTINGS_MAXHISTORY_TT      3122
#define IDS_SETTINGS_CACHEDEFAULT_TT    3123
#define IDS_SETTINGS_CACHESHELL_TT      3124
#define IDS_SETTINGS_CACHENONE_TT       3125
#define IDS_SETTINGS_SAVEDDATA_LOGHIST_TT 3126
#define IDS_SETTINGS_SAVEDDATA_URLHIST_TT 3127
#define IDS_SETTINGS_SAVEDDATA_RESIZABLE_TT 3128
#define IDS_SETTINGS_SAVEDDATA_AUTH_TT  3129
#define IDS_SETTINGS_DOTNETHACK_TT      3130
#define IDS_SETTINGS_RESTARTSYSTEM      3131
#define IDS_SETTINGS_ASPHACKWARNING     3132
#define IDS_CHECKNEWER_YOURVERSION      3200
#define IDS_CHECKNEWER_CURRENTVERSION   3201
#define IDS_CHECKNEWER_YOURUPTODATE     3202
#define IDS_CHECKNEWER_NEWERVERSIONAVAILABLE 3203
#define IDS_CHECKNEWER_NETERROR         3204
#define IDS_STATUSLIST_COLFILE          3300
#define IDS_STATUSLIST_COLSTATUS        3301
#define IDS_STATUSLIST_COLREMOTESTATUS  3302
#define IDS_STATUSLIST_COLTEXTSTATUS    3303
#define IDS_STATUSLIST_COLPROPSTATUS    3304
#define IDS_STATUSLIST_COLREMOTETEXTSTATUS 3305
#define IDS_STATUSLIST_COLREMOTEPROPSTATUS 3306
#define IDS_STATUSLIST_COLURL           3307
#define IDS_STATUSLIST_COLEXT           3308
#define IDS_STATUSLIST_COLLOCK          3309
#define IDS_STATUSLIST_COLLOCKCOMMENT   3310
#define IDS_STATUSLIST_COLAUTHOR        3311
#define IDS_STATUSLIST_COLDATE          3312
#define IDS_STATUSLIST_COLREVISION      3313
#define IDS_STATUSLIST_MULTIPLETARGETS  3320
#define IDS_STATUSLIST_PROPONLY         3321
#define IDS_STATUSLIST_COPYFROM         3322
#define IDS_STATUSLIST_SWITCHEDTO       3323
#define IDS_STATUSLIST_CONTEXT_ADD      3330
#define IDS_STATUSLIST_CONTEXT_EXPLORE  3331
#define IDS_STATUSLIST_CONTEXT_RESOLVED 3332
#define IDS_STATUSLIST_CONTEXT_COMMIT   3333
#define IDS_STATUSLIST_CONTEXT_PROPERTIES 3334
#define IDS_IDS_STATUSLIST_CONTEXT_COPY 3335
#define IDS_STATUSLIST_CONTEXT_COPY     3335
#define IDS_STATUSLIST_CONTEXT_COPYEXT  3336
#define IDS_STATUSLIST_LOCKBROKEN       3340
#define IDS_STATUSLIST_LOCKSTOLEN       3341
#define IDS_STATUSLIST_NESTED           3350
#define IDS_STATUSLIST_BUSYMSG          3360
#define IDS_STATUSLIST_EMPTYMSG         3361
#define IDS_PROGRS_CONFLICTSOCCURED_WARNING 3500
#define IDS_PROGRS_CONFLICTSOCCURED     3501
#define IDS_PROGRS_DRYRUN               3502
#define IDS_PROGRS_TITLE_RENAME         3530
#define IDS_PROGRS_TITLE_LOCK           3531
#define IDS_PROGRS_TITLE_UNLOCK         3532
#define IDS_PROGRS_CLOSE_MANUAL         3540
#define IDS_PROGRS_CLOSE_NOERROR        3541
#define IDS_PROGRS_CLOSE_NOCONFLICTS    3542
#define IDS_PROGRS_CLOSE_NOMERGES       3543
#define IDS_PROGRS_NONRECURSIVEHINT     3580
#define IDS_PROGRS_PATHATREV            3600
#define IDS_PROGRS_UPDATEPATH           3601
#define IDS_SSL_SAVE_CERTPATH           3700
#define IDS_REPOSTATUS_HEADREV          3800
#define IDS_REPOSTATUS_WCINFO           3801
#define IDS_STATGRAPH_COMMITSBYAUTHOR   3900
#define IDS_STATGRAPH_COMMITSBYDATE     3901
#define IDS_STATGRAPH_COMMITSBYDATEX    3902
#define IDS_STATGRAPH_COMMITSBYDATEY    3903
#define IDS_STATGRAPH_COMMITSBYAUTHORX  3904
#define IDS_STATGRAPH_COMMITSBYAUTHORY  3905
#define IDS_STATGRAPH_STATS             3906
#define IDS_STATGRAPH_OTHERGROUP        3907
#define IDS_SVNERR_CHECKPATHORURL       4000
#define IDS_SVNERR_RUNCLEANUP           4001
#define IDS_SVNERR_UPDATEFIRST          4002
#define IDS_SVNERR_CLEANUPORFRESHCHECKOUT 4003
#define IDS_SVNERR_UNLOCKFAILED         4004
#define IDS_SVNERR_UNLOCKFAILEDNOLOCK   4005
#define IDS_CLIPBOARD_PROGRESS_DEST     4100
#define IDS_SVNACTION_SKIPMISSING       4200
#define IDS_SVNACTION_ADDING            4201
#define IDS_SVNACTION_DELETING          4202
#define IDS_SVNACTION_MERGED            4203
#define IDS_SVNACTION_CONFLICTED        4204
#define IDS_SVNACTION_UNLOCKED          4205
#define IDS_SVNACTION_LOCKEDBY          4206
#define IDS_SVNACTION_FAILEDLOCK        4207
#define IDS_SVNACTION_FAILEDUNLOCK      4208
#define IDS_SVN_SUMMARIZENORMAL         4220
#define IDS_SVN_SUMMARIZEADDED          4221
#define IDS_SVN_SUMMARIZEMODIFIED       4222
#define IDS_SVN_SUMMARIZEDELETED        4223
#define IDS_REVGRAPH_PROGTITLE          4300
#define IDS_REVGRAPH_PROGGETREVS        4301
#define IDS_REVGRAPH_PROGCURRENTREV     4302
#define IDS_REVGRAPH_PROGANALYZE        4303
#define IDS_REVGRAPH_PROGANALYZEREV     4304
#define IDS_REVGRAPH_PROGCANCEL         4305
#define IDS_REVGRAPH_PROGCHECKFORWARD   4306
#define IDS_REVGRAPH_PROGCHECKFORWARDREV 4307
#define IDS_REVGRAPH_BOXTOOLTIP         4340
#define IDS_REVGRAPH_STATUSBARURL       4341
#define IDS_REVGRAPH_STATUSBARNUMNODES  4342
#define IDS_REVGRAPH_BOXREVISIONTITLE   4343
#define IDS_REVGRAPH_SAVEPIC            4350
#define IDS_REVGRAPH_ERR_GDIINIT        4360
#define IDS_REVGRAPH_ERR_NOBITMAP       4361
#define IDS_REVGRAPH_ERR_NOENCODER      4362
#define IDS_REVGRAPH_ERR_NOGRAPH        4363
#define IDS_REVGRAPH_POPUP_COMPAREREVS  4380
#define IDS_REVGRAPH_POPUP_COMPAREHEADS 4381
#define IDS_REVGRAPH_POPUP_UNIDIFFREVS  4382
#define IDS_REVGRAPH_POPUP_UNIDIFFHEADS 4383
#define IDS_MERGE_SELECTRANGE           4400
#define IDS_MERGE_SELECTENDREVISION     4401
#define IDS_MERGE_SELECTSTARTREVISION   4402
#define IDS_SVNPROGRESS_MENUUSETHEIRS   4500
#define IDS_SVNPROGRESS_MENUUSEMINE     4501
#define IDS_SVNPROGRESS_MENUOPENPARENT  4502
#define IDS_SVNPROGRESS_RESOLVED        4510
#define IDS_SVNPROGRESS_UPDATEANDRETRY  4520
#define IDS_LOCK_MESSAGEHINT            5000
#define IDS_LOCK_STEALCHECK             5001
#define IDS_FILEDIFF_FILE               5100
#define IDS_FILEDIFF_COMMENT            5101
#define IDS_FILEDIFF_ACTION             5101
#define IDS_FILEDIFF_COMMENTCOPY        5102
#define IDS_FILEDIFF_WAIT               5102
#define IDS_FILEDIFF_COMMENTRENAMED     5103
#define IDS_FILEDIFF_POPBLAME           5150
#define IDS_FILEDIFF_SWITCHLEFTRIGHT_TT 5190
#define IDS_CREATEPATCH_ADDEDFOLDERS    5400
#define IDS_SVN_PROGRESS_SPEED          5700
#define IDS_SVN_PROGRESS_TOTALTRANSFERRED 5701
#define IDS_SVN_PROGRESS_TOTALMBTRANSFERRED 5702
#define IDS_SVN_PROGRESS_TOTALANDSPEED  5703
#define IDS_SVN_PROGRESS_TOTALBYTESTRANSFERRED 5704
#define IDS_SCIEDIT_UNDO                6000
#define IDS_SCIEDIT_REDO                6001
#define IDS_SCIEDIT_CUT                 6002
#define IDS_SCIEDIT_COPY                6003
#define IDS_SCIEDIT_PASTE               6004
#define IDS_SCIEDIT_SELECTALL           6005
#define IDS_SCIEDIT_ADDWORD             6006
#define IDS_COLOURPICKER_CUSTOMTEXT     7000
#define IDS_COLOURPICKER_DEFAULTTEXT    7001
#define IDS_COPYDLG_FROMURL             8000
#define IDS_EDITPROPS_NUMPATHS          9000
#define IDS_EDITPROPS_DIFFERENTPROPVALUES 9001
#define IDS_EDITPROPS_RECURSIVEREMOVEQUESTION 9002
#define IDS_EDITPROPS_RECURSIVE         9003
#define IDS_EDITPROPS_NOTRECURSIVE      9004
#define IDS_EDITPROPS_CANCEL            9005
#define IDS_EDITPROPS_ADDBUTTON         9006
#define IDS_EDITPROPS_EDITBUTTON        9007
#define IDS_EDITPROPS_ADDTITLE          9007
#define IDS_EDITPROPS_EDITTITLE         9008
#define IDS_EDITPROPS_BINVALUE          9020
#define ID_FILE_SAVEGRAPHAS             32771
#define ID_VIEW_ZOOMIN                  32772
#define ID_VIEW_ZOOMOUT                 32773
#define ID_MENUHELP                     32781
#define ID_MENUEXIT                     32782
#define ID_VIEW_COMPAREREVISIONS        32783
#define ID_VIEW_COMPAREHEADREVISIONS    32784
#define ID_VIEW_UNIFIEDDIFF             32785
#define ID_VIEW_UNIFIEDDIFFOFHEADREVISIONS 32786
#define ID_VIEW_SHOWALLREVISIONS        32796
#define ID_VIEW_ARRANGEDBYPATH          32799
#define ID_REVGRAPH_ZOOMCOMBO           32800
#define ID_VIEW_ZOOM100                 32803
#define ID_VIEW_ZOOMALL                 32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        235
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1312
#define _APS_NEXT_SYMED_VALUE           195
#endif
#endif
