//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by f:\Development\Svn\TortoiseSVN\src\Languages\TortoiseProcENG.rc
//
#define IDR_MANIFEST                    1
#define IDR_MAINFRAME                   1
#define IDD_SETTINGSPROXY               102
#define IDD_SETTINGSOVERLAY             106
#define IDD_ABOUT                       129
#define IDD_LOGMESSAGE                  130
#define IDD_PROMPT                      131
#define IDD_CHECKOUT                    133
#define IDD_SVNPROGRESS                 134
#define IDD_LOGPROMPT                   135
#define IDD_IMPORT                      139
#define IDD_SWITCH                      140
#define IDD_MERGE                       141
#define IDD_COPY                        142
#define IDD_SETTINGSMAIN                143
#define IDR_ANIMATION                   148
#define IDR_MOVEANI                     149
#define IDD_RENAME                      151
#define IDD_UPDATE                      152
#define IDD_REPOSITORY_BROWSER          153
#define IDD_ADD                         155
#define IDD_RELOCATE                    157
#define IDD_CHANGEDFILES                158
#define IDD_SETTINGSMENU                159
#define IDD_SIMPLEPROMPT                160
#define IDD_INPUTDLG                    161
#define IDD_BLAME                       162
#define IDR_SEARCH                      163
#define IDD_SETTINGSPROGS               163
#define IDI_DRIVES                      164
#define IDD_URL                         164
#define IDI_SSH                         165
#define IDI_PROXY                       166
#define IDI_MISC                        167
#define IDB_LOGOFLIPPED                 168
#define IDB_BITMAP1                     169
#define IDB_TTF_BMP                     169
#define IDD_SETTINGSPROGSADV            170
#define IDD_TOOLASSOC                   171
#define IDS_CHSTAT_FILECOL              1000
#define IDS_CHSTAT_WCCOL                1001
#define IDS_CHSTAT_REPOCOL              1002
#define IDC_LOGLIST                     1003
#define IDC_PASSEDIT                    1004
#define IDC_INFOTEXT                    1005
#define IDC_URL                         1009
#define IDC_CHECKOUTDIRECTORY           1010
#define IDC_SVNPROGRESS                 1013
#define IDC_LOGMESSAGE                  1014
#define IDC_LOGMSG                      1015
#define IDC_REPURL                      1015
#define IDC_TOURL                       1015
#define IDC_EXTDIFF                     1015
#define IDC_MODNAME                     1016
#define IDC_EXTMERGE                    1016
#define IDC_MESSAGE                     1017
#define IDC_DIFFVIEWER                  1017
#define IDC_REV                         1018
#define IDC_NEWEST                      1019
#define IDC_BRANCH                      1020
#define IDC_EXTDIFFBROWSE               1021
#define IDC_EXTMERGEBROWSE              1022
#define IDC_CHANGEDDIRS                 1023
#define IDC_ENABLE                      1023
#define IDC_MODULENAMECHECK             1023
#define IDC_SAVECHECK                   1023
#define IDC_ADDBEFORECOMMIT             1023
#define IDC_MENU1                       1023
#define IDC_DIFFVIEWERROWSE             1024
#define IDC_MENU3                       1024
#define IDC_MENU4                       1026
#define IDC_NAME                        1027
#define IDC_REVNUM                      1027
#define IDC_SERVERADDRESS               1027
#define IDC_TEMPEXTENSIONS              1027
#define IDC_REVISON_START               1027
#define IDC_MENU5                       1027
#define IDC_USEREDIT                    1027
#define IDC_MENU6                       1028
#define IDC_URLCOMBO                    1029
#define IDC_MENU7                       1029
#define IDC_COMBO1                      1030
#define IDC_MENU8                       1030
#define IDC_FONTNAMES                   1030
#define IDC_BUTTON1                     1031
#define IDC_LOGBUTTON                   1031
#define IDC_MENU9                       1031
#define IDC_FINDBRANCHSTART             1031
#define IDC_GETALL                      1031
#define IDC_EDITCONFIG                  1031
#define IDC_RADIO1                      1032
#define IDC_REVISION_HEAD               1032
#define IDC_MENU10                      1032
#define IDC_RADIO2                      1033
#define IDC_REVISION_N                  1033
#define IDC_MENU11                      1033
#define IDC_REVISION_NUM                1034
#define IDC_BROWSE                      1035
#define IDC_EDIT2                       1036
#define IDC_BROWSE2                     1036
#define IDC_CHECKOUTDIRECTORY_BROWSE    1036
#define IDC_REPOS_TREE                  1037
#define IDC_SERVERPORT                  1038
#define IDC_USERNAME                    1039
#define IDC_PASSWORD                    1040
#define IDC_TIMEOUT                     1041
#define IDC_STATICURL                   1042
#define IDC_LIST1                       1043
#define IDC_FILELIST                    1043
#define IDC_ADDLIST                     1043
#define IDC_CHANGEDLIST                 1043
#define IDC_MENULIST                    1043
#define IDC_LANGUAGECOMBO               1044
#define IDC_FROMURL                     1045
#define IDC_MENU12                      1045
#define IDC_COMMIT_TO                   1046
#define IDC_MENU13                      1046
#define IDC_MENU14                      1047
#define IDC_REMOVABLE                   1048
#define IDC_MENU15                      1048
#define IDC_NETWORK                     1049
#define IDC_MENU16                      1049
#define IDC_FIXED                       1050
#define IDC_MENU17                      1050
#define IDC_CDROM                       1051
#define IDC_MENU18                      1051
#define IDC_HINTLABEL                   1052
#define IDC_MENU19                      1052
#define IDC_REVISION_END                1053
#define IDC_MENU20                      1053
#define IDC_VERSIONABOUT                1054
#define IDC_MENU21                      1054
#define IDC_STATIC1                     1055
#define IDC_CHECK23                     1055
#define IDC_MENU22                      1055
#define IDC_STATIC2                     1056
#define IDC_STATIC3                     1057
#define IDC_STATIC4                     1058
#define IDC_BUTTON2                     1059
#define IDC_CANCEL                      1060
#define IDC_CHECK2                      1061
#define IDC_NOREMOVELOGMSG              1061
#define IDC_MENU2                       1061
#define IDC_UNKNOWN                     1061
#define IDC_MENU23                      1063
#define IDC_INPUTTEXT                   1064
#define IDC_HINTTEXT                    1065
#define IDC_AUTOCLOSE                   1066
#define IDC_SELECTALL                   1067
#define IDC_SSHCLIENT                   1068
#define IDC_SSHBROWSE                   1069
#define IDC_DEFAULTLOG                  1071
#define IDC_CHECK1                      1073
#define IDC_MENU24                      1073
#define IDC_DONTCONVERT                 1073
#define IDC_RAM                         1073
#define IDC_EXPORT_CHECKOUTDIR          1074
#define IDC_VERSIONBOX                  1075
#define IDC_LABEL                       1076
#define IDC_EDIT1                       1077
#define IDC_MSGVIEW                     1077
#define IDC_DRIVEGROUP                  1079
#define IDC_PROXYGROUP                  1080
#define IDC_SSHGROUP                    1081
#define IDC_MISCGROUP                   1082
#define IDC_COMMITGROUP                 1083
#define IDC_WEBLINK                     1084
#define IDC_SUPPORTLINK                 1085
#define IDC_FONTSIZES                   1086
#define IDC_REVTEXT                     1087
#define IDC_CHECK3                      1088
#define IDC_COMMITFILETIMES             1088
#define IDC_DIFFVIEWERBROWSE            1089
#define IDC_EXTDIFFADVANCED             1090
#define IDC_EXTDIFF_OFF                 1091
#define IDC_EXTDIFF_ON                  1092
#define IDC_EXTMERGEADVANCED            1093
#define IDC_EXTMERGE_OFF                1094
#define IDC_EXTMERGE_ON                 1095
#define IDC_DIFFVIEWER_OFF              1096
#define IDC_DIFFVIEWER_ON               1097
#define IDC_ADDTOOL                     1098
#define IDC_EDITTOOL                    1099
#define IDC_REMOVETOOL                  1100
#define IDS_AUTH_USERNAME               1100
#define IDC_TOOLS                       1101
#define IDS_AUTH_PASSWORD               1101
#define IDC_TOOLLISTCTRL                1101
#define IDC_EXTEDIT                     1102
#define IDC_TOOLEDIT                    1103
#define IDC_TOOLBROWSE                  1104
#define IDC_SHORTDATEFORMAT             1105
#define IDC_SUMMARYTEXT                 1106
#define IDS_MSGBOX_ABORT                1154
#define IDS_MSGBOX_RETRY                1155
#define IDS_MSGBOX_IGNORE               1156
#define IDS_MSGBOX_CANCEL               1157
#define IDS_MSGBOX_TRYAGAIN             1158
#define IDS_MSGBOX_CONTINUE             1159
#define IDS_MSGBOX_OK                   1160
#define IDS_MSGBOX_YES                  1161
#define IDS_MSGBOX_NO                   1162
#define IDS_SVNACTION_ADD               1163
#define IDS_SVNACTION_COPY              1164
#define IDS_SVNACTION_DELETE            1165
#define IDS_SVNACTION_RESTORE           1166
#define IDS_SVNACTION_REVERT            1167
#define IDS_SVNACTION_RESOLVE           1168
#define IDS_SVNACTION_UPDATE            1169
#define IDS_SVNACTION_COMPLETED         1170
#define IDS_SVNACTION_EXTERNAL          1171
#define IDS_SVNACTION_MODIFIED          1172
#define IDS_SVNACTION_REPLACED          1173
#define IDS_SVNACTION_POSTFIX           1174
#define IDS_SVNACTION_FAILEDREVERT      1175
#define IDS_SVNACTION_STATUS            1176
#define IDS_SVNACTION_SKIP              1177
#define IDS_PROGS_EXTCOL                1178
#define IDS_PROGS_TOOLCOL               1179
#define IDS_LOG_FILE                    1180
#define IDS_SVN_USERCANCELLED           1181
#define IDS_LOG_SIZE                    1182
#define IDS_REPO_BROWSEREV              1190
#define IDS_SSL_CERTIFICATETYPE         1200
#define IDS_SSL_ACCEPTQUESTION          1201
#define IDS_SSL_CLIENTCERTIFICATEFILENAME 1202
#define IDS_SSL_PEM                     1203
#define IDS_SSL_PKCS12                  1204
#define IDS_IMPORT_DEFAULTMSG           1205
#define IDS_LOG_MESSAGE                 1207
#define IDS_LOG_REVISION                1208
#define IDS_LOG_AUTHOR                  1209
#define IDS_LOG_DATE                    1210
#define IDS_LOG_REVERT_CONFIRM          1211
#define IDS_LOG_POPUP_COMPARE           1212
#define IDS_LOG_POPUP_SAVE              1213
#define IDS_LOG_POPUP_COMPARETWO        1214
#define IDS_LOG_POPUP_UPDATE            1215
#define IDS_LOG_POPUP_COPY              1216
#define IDS_LOGPROMPT_FILE              1217
#define IDS_LOGPROMPT_STATUS            1218
#define IDS_LOGPROMPT_ASKADD            1219
#define IDS_LOGPROMPT_NOTHINGTOCOMMIT   1220
#define IDS_PROGRS_ATREV                1221
#define IDS_PROGRS_ACTION               1222
#define IDS_PROGRS_PATH                 1223
#define IDS_PROGRS_TITLEFIN             1224
#define IDS_PROGRS_TITLE_CHECKOUT       1225
#define IDS_PROGRS_TITLE_IMPORT         1226
#define IDS_PROGRS_TITLE_UPDATE         1227
#define IDS_PROGRS_TITLE_COMMIT         1228
#define IDS_PROGRS_TITLE_ADD            1229
#define IDS_PROGRS_TITLE_REVERT         1230
#define IDS_PROGRS_TITLE_RESOLVE        1231
#define IDS_PROGRS_TITLE_SWITCH         1232
#define IDS_PROGRS_TITLE_EXPORT         1233
#define IDS_PROGRS_TITLE_MERGE          1234
#define IDS_PROGRS_TITLE_COPY           1235
#define IDS_PROGRS_MIMETYPE             1236
#define IDS_PROGRS_COPY_WARNING         1238
#define IDS_PROGRS_COMMITT_TRUNK        1239
#define IDS_SETTINGS_SELECTDIFF         1241
#define IDS_SETTINGS_SELECTDIFFVIEWER   1242
#define IDS_SETTINGS_SELECTMERGE        1243
#define IDS_SETTINGS_SELECTSSH          1244
#define IDS_SETTINGS_EXTDIFF_TT         1245
#define IDS_SETTINGS_EXTDIFFBROWSE_TT   1246
#define IDS_SETTINGS_CHANGEDDIRS_TT     1247
#define IDS_SETTINGS_TEMPEXTENSIONS_TT  1248
#define IDS_SETTINGS_ADDBEFORECOMMIT_TT 1249
#define IDS_SETTINGS_EXTMERGE_TT        1250
#define IDS_SETTINGS_PROXYSERVER_TT     1251
#define IDS_SETTINGS_DIFFVIEWER_TT      1252
#define IDS_SETTINGS_AUTOCLOSE_TT       1253
#define IDS_UTILS_SELECTTEXTVIEWER      1254
#define IDS_SETTINGS_DONTCONVERTBASE_TT 1255
#define IDS_PROC_WARNREVERT             1256
#define IDS_PROC_CLEANUPFINISHED        1257
#define IDS_PROC_REPOCREATEERR          1258
#define IDS_PROC_EXPORT_1               1259
#define IDS_PROC_EXPORT_2               1260
#define IDS_PROC_EXPORT_3               1261
#define IDS_PROC_EXPORT_4               1262
#define IDS_PROC_COPY_SUCCESS           1263
#define IDS_PROC_SETTINGS_TITLE         1264
#define IDS_PROC_DELETE_CONFIRM         1265
#define IDS_PROC_OVERWRITE_CONFIRM      1266
#define IDS_PROC_REPOCREATEFINISHED     1267
#define IDS_PROC_RELOCATEFINISHED       1268
#define IDS_PROC_MOVING                 1269
#define IDS_PROC_RELOCATING             1270
#define IDS_APPNAME                     1271
#define IDS_MSGBOX_DONOTSHOW            1272
#define IDS_PROC_COPYING                1273
#define IDS_PROC_COPYINGPROG            1274
#define IDS_PROC_MOVINGPROG             1275
#define IDS_PROC_CPYMVPROG2             1276
#define IDS_PROC_ENTERURL               1277
#define IDS_SETTINGS_NOREMOVELOGMSG_TT  1278
#define IDS_SETTINGS_SHORTDATEFORMAT_TT 1279
#define IDS_ERR_THREADSTARTFAILED       1281
#define IDS_ERR_EXTDIFFSTART            1282
#define IDS_ERR_NOCOMMAND               1283
#define IDS_ERR_NOCOMMANDVALUE          1284
#define IDS_ERR_NOSTATUS                1285
#define IDS_ERR_CLEANUP                 1286
#define IDS_ERR_NOURLOFFILE             1287
#define IDS_ERR_WCCHANGED               1288
#define IDS_ERR_COPYFILES               1289
#define IDS_ERR_EXTMERGESTART           1290
#define IDS_ERR_NOTUPTODATE             1291
#define IDS_ERR_FAILEDIGNOREPROPERTY    1292
#define IDS_ERR_DIFFVIEWSTART           1293
#define IDS_ERR_SSL_VALIDATE            1294
#define IDS_ERR_SSL_UNKNOWNCA           1295
#define IDS_ERR_SSL_CNMISMATCH          1296
#define IDS_ERR_SSL_EXPIREDORNOTYETVALID 1297
#define IDS_SSL_ACCEPTALWAYS            1298
#define IDS_SSL_ACCEPTTEMP              1299
#define IDS_SSL_REJECT                  1300
#define IDS_ERR_SSL_NOTYETVALID         1301
#define IDS_ERR_SSL_EXPIRED             1302
#define IDS_ERR_COPYITSELF              1303
#define IDS_WARN_FOLDERNOTEXIST         1400
#define IDS_WARN_SHAREFILEACCESS        1401
#define IDS_CHECKOUT_TT_DIR             1500
#define IDS_CHECKOUT_EXPORTDIR          1501
#define IDS_IMPORT_TT_MODULENAMECHECK   1510
#define IDS_IMPORT_TT_TEMPFILES         1511
#define IDS_PROC_RENAME                 1550
#define IDS_REPOBROWSE_SAVEAS           1600
#define IDS_REPOBROWSE_SHOWLOG          1601
#define IDS_REPOBROWSE_OPEN             1602
#define IDS_REPOBROWSE_COPY             1603
#define IDS_REPOBROWSE_DELETE           1604
#define IDS_REPOBROWSE_IMPORT           1605
#define IDS_REPOBROWSE_RENAME           1606
#define IDS_REPOBROWSE_MKDIR            1607
#define IDS_REPOBROWSE_IMPORTFOLDER     1608
#define IDS_ABOUTVERSION                1700
#define IDS_ABOUTVERSIONBOX             1701
#define IDS_DLGTITLE_ADD_DIFF_TOOL      1750
#define IDS_DLGTITLE_ADD_MERGE_TOOL     1751
#define IDS_DLGTITLE_EDIT_DIFF_TOOL     1752
#define IDS_DLGTITLE_EDIT_MERGE_TOOL    1753
#define IDS_DLGTITLE_ADV_DIFF           1754
#define IDS_DLGTITLE_ADV_MERGE          1755
#define IDS_LOG_POPUP_DIFF              1800
#define IDS_LOG_POPUP_REVERTREV         1801
#define IDS_LOG_POPUP_GNUDIFF           1802
#define IDS_LOG_POPUP_FIND              1803
#define IDS_LOG_COPY_SUCCESS            1830
#define IDS_PROGRESSGETFILE             1900
#define IDS_PROGRESSREVISION            1901
#define IDS_PROGRESSWAIT                1902
#define IDS_INPUT_ENTERLOG              2000
#define IDS_INPUT_LOGTITLE              2001
#define IDS_INPUT_REMOVELOGMSG          2002
#define IDS_INPUT_ADDLOGMSG             2003
#define IDS_INPUT_COPYLOGMSG            2004
#define IDS_INPUT_MKDIRLOGMSG           2005
#define IDS_INPUT_MOVELOGMSG            2006
#define IDS_BLAME_PROGRESSTITLE         2100
#define IDS_BLAME_PROGRESSINFO          2101
#define IDS_BLAME_PROGRESSCANCEL        2102
#define IDS_BLAME_PROGRESSINFO2         2103
#define IDS_BLAME_PROGRESSINFOSTART     2104
#define IDS_MENUREFRESH                 2150
#define IDS_LOG_COMPAREWITHBASE         2200
#define IDS_LOG_BROWSEREPO              2201
#define IDS_PROC_ENTERURLLABEL          2300
#define IDS_PROC_PATCHTITLE             2301
#define IDS_PROC_SAVEPATCHTO            2302
#define IDS_PROC_REPOCREATESHAREWARN    2303
#define IDS_DIFF_WCNAME                 2400
#define IDS_DIFF_BASENAME               2401
#define IDS_COMMONFILEFILTER            2500
#define IDS_PROGRAMSFILEFILTER          2501
#define IDS_CERTIFICATESFILEFILTER      2502
#define IDS_PATCHFILEFILTER             2503
#define IDS_CHECKUPDATE_SUMMARY         2600
#define IDS_LOGPROMPT_EXTERNALS         2700

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
