//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TortoiseProcDEU.rc
//
#define IDR_MANIFEST                    1
#define IDR_MAINFRAME                   1
#define IDD_SETTINGSPROXY               102
#define IDD_SETTINGSOVERLAY             106
#define IDD_ABOUT                       129
#define IDD_LOGMESSAGE                  130
#define IDD_PROMPT                      131
#define IDB_LOGOFLIPPED                 132
#define IDD_CHECKOUT                    133
#define IDD_SVNPROGRESS                 134
#define IDD_LOGPROMPT                   135
#define IDD_IMPORT                      139
#define IDD_SWITCH                      140
#define IDD_MERGE                       141
#define IDD_COPY                        142
#define IDD_SETTINGSMAIN                143
#define IDR_AVI1                        148
#define IDR_ANIMATION                   148
#define IDD_RENAME                      151
#define IDD_UPDATE                      152
#define IDD_REPOSITORY_BROWSER          153
#define IDS_MSGBOX_ABORT                154
#define IDS_MSGBOX_RETRY                155
#define IDD_ADD                         155
#define IDS_MSGBOX_IGNORE               156
#define IDS_MSGBOX_CANCEL               157
#define IDD_RELOCATE                    157
#define IDS_MSGBOX_TRYAGAIN             158
#define IDS_MSGBOX_CONTINUE             159
#define IDS_MSGBOX_OK                   160
#define IDS_MSGBOX_YES                  161
#define IDS_MSGBOX_NO                   162
#define IDS_SVNACTION_ADD               163
#define IDS_SVNACTION_COPY              164
#define IDS_SVNACTION_DELETE            165
#define IDS_SVNACTION_RESTORE           166
#define IDS_SVNACTION_REVERT            167
#define IDS_SVNACTION_RESOLVE           168
#define IDS_SVNACTION_UPDATE            169
#define IDS_SVNACTION_COMPLETED         170
#define IDS_SVNACTION_EXTERNAL          171
#define IDS_SVNACTION_MODIFIED          172
#define IDS_SVNACTION_REPLACED          173
#define IDS_SVNACTION_POSTFIX           174
#define IDS_SVNACTION_FAILEDREVERT      175
#define IDS_SVNACTION_STATUS            176
#define IDS_SVNACTION_SKIP              177
#define IDS_STRING178                   178
#define IDS_STRING179                   179
#define IDS_STRING180                   180
#define IDS_SVN_USERCANCELLED           181
#define IDS_STRING182                   182
#define IDS_STRING183                   183
#define IDS_STRING184                   184
#define IDS_STRING185                   185
#define IDS_STRING186                   186
#define IDS_STRING187                   187
#define IDS_STRING188                   188
#define IDS_STRING189                   189
#define IDS_STRING190                   190
#define IDS_STATUSNONE                  191
#define IDS_STATUSUNVERSIONED           192
#define IDS_STATUSNORMAL                193
#define IDS_STATUSADDED                 194
#define IDS_STATUSABSENT                195
#define IDS_STATUSDELETED               196
#define IDS_STATUSREPLACED              197
#define IDS_STATUSMODIFIED              198
#define IDS_STATUSMERGED                199
#define IDS_STATUSCONFLICTED            200
#define IDS_STATUSOBSTRUCTED            201
#define IDS_STRING202                   202
#define IDS_STRING203                   203
#define IDS_STRING204                   204
#define IDS_IMPORT_DEFAULTMSG           205
#define IDS_STRING206                   206
#define IDS_STRING207                   207
#define IDS_LOG_REVISION                208
#define IDS_LOG_AUTHOR                  209
#define IDS_LOG_DATE                    210
#define IDS_STRING211                   211
#define IDS_LOG_POPUP_COMPARE           212
#define IDS_LOG_POPUP_SAVE              213
#define IDS_STRING214                   214
#define IDS_LOG_POPUP_COMPARETWO        214
#define IDS_STRING215                   215
#define IDS_LOG_POPUP_UPDATE            215
#define IDS_STRING216                   216
#define IDS_LOGPROMPT_FILE              217
#define IDS_LOGPROMPT_STATUS            218
#define IDS_STRING219                   219
#define IDS_LOGPROMPT_ASKADD            219
#define IDS_STRING220                   220
#define IDS_PROGRS_ATREV                221
#define IDS_PROGRS_ACTION               222
#define IDS_PROGRS_PATH                 223
#define IDS_PROGRS_TITLEFIN             224
#define IDS_PROGRS_TITLE_CHECKOUT       225
#define IDS_PROGRS_TITLE_IMPORT         226
#define IDS_PROGRS_TITLE_UPDATE         227
#define IDS_PROGRS_TITLE_COMMIT         228
#define IDS_PROGRS_TITLE_ADD            229
#define IDS_PROGRS_TITLE_REVERT         230
#define IDS_PROGRS_TITLE_RESOLVE        231
#define IDS_PROGRS_TITLE_SWITCH         232
#define IDS_PROGRS_TITLE_EXPORT         233
#define IDS_PROGRS_TITLE_MERGE          234
#define IDS_PROGRS_TITLE_COPY           235
#define IDS_STRING236                   236
#define IDS_STRING237                   237
#define IDS_PROGRS_COPY_WARNING         238
#define IDS_STRING239                   239
#define IDS_PROGRS_COMMITT_TRUNK        239
#define IDS_STRING240                   240
#define IDS_SETTINGS_SELECTDIFF         241
#define IDS_STRING242                   242
#define IDS_STRING243                   243
#define IDS_STRING244                   244
#define IDS_SETTINGS_EXTDIFF_TT         245
#define IDS_SETTINGS_EXTDIFFBROWSE_TT   246
#define IDS_SETTINGS_CHANGEDDIRS_TT     247
#define IDS_STRING248                   248
#define IDS_SETTINGS_TEMPEXTENSIONS_TT  248
#define IDS_STRING249                   249
#define IDS_SETTINGS_ADDBEFORECOMMIT_TT 249
#define IDS_STRING250                   250
#define IDS_SETTINGS_EXTMERGE_TT        250
#define IDS_SETTINGS_PROXYSERVER_TT     251
#define IDS_STRING252                   252
#define IDS_STRING253                   253
#define IDS_STRING254                   254
#define IDS_STRING255                   255
#define IDS_PROC_WARNREVERT             256
#define IDS_PROC_CLEANUPFINISHED        257
#define IDS_PROC_REPOCREATEERR          258
#define IDS_PROC_EXPORT_1               259
#define IDS_PROC_EXPORT_2               260
#define IDS_PROC_EXPORT_3               261
#define IDS_PROC_EXPORT_4               262
#define IDS_PROC_COPY_SUCCESS           263
#define IDS_PROC_SETTINGS_TITLE         264
#define IDS_PROC_DELETE_CONFIRM         265
#define IDS_STRING266                   266
#define IDS_PROC_OVERWRITE_CONFIRM      266
#define IDS_STRING267                   267
#define IDS_PROC_REPOCREATEFINISHED     267
#define IDS_STRING268                   268
#define IDS_PROC_RELOCATEFINISHED       268
#define IDS_STRING269                   269
#define IDS_STRING270                   270
#define IDS_APPNAME                     271
#define IDS_STRING272                   272
#define IDS_MSGBOX_DONOTSHOW            272
#define IDS_STRING273                   273
#define IDS_STRING274                   274
#define IDS_STRING275                   275
#define IDS_STRING276                   276
#define IDS_STRING277                   277
#define IDS_STRING278                   278
#define IDS_STRING279                   279
#define IDS_STRING280                   280
#define IDS_ERR_THREADSTARTFAILED       281
#define IDS_ERR_EXTDIFFSTART            282
#define IDS_ERR_NOCOMMAND               283
#define IDS_ERR_NOCOMMANDVALUE          284
#define IDS_ERR_NOSTATUS                285
#define IDS_ERR_CLEANUP                 286
#define IDS_ERR_NOURLOFFILE             287
#define IDS_ERR_WCCHANGED               288
#define IDS_ERR_COPYFILES               289
#define IDS_STRING290                   290
#define IDS_ERR_EXTMERGESTART           290
#define IDS_STRING291                   291
#define IDS_STRING292                   292
#define IDS_STRING293                   293
#define IDS_STRING294                   294
#define IDS_STRING295                   295
#define IDS_WARN_FOLDERNOTEXIST         400
#define IDS_CHECKOUT_TT_DIR             500
#define IDS_IMPORT_TT_MODULENAMECHECK   510
#define IDS_REPOBROWSE_SAVEAS           600
#define IDS_REPOBROWSE_SHOWLOG          601
#define IDS_REPOBROWSE_OPEN             602
#define IDS_ABOUTVERSION                700
#define IDC_LOGLIST                     1003
#define IDC_PASSEDIT                    1004
#define IDC_INFOTEXT                    1005
#define IDC_URL                         1009
#define IDC_CHECKOUTDIRECTORY           1010
#define IDC_SVNPROGRESS                 1013
#define IDC_LOGMESSAGE                  1014
#define IDC_LOGMSG                      1015
#define IDC_REPURL                      1015
#define IDC_TOURL                       1015
#define IDC_EXTDIFF                     1015
#define IDC_MODNAME                     1016
#define IDC_EXTMERGE                    1016
#define IDC_MESSAGE                     1017
#define IDC_REV                         1018
#define IDC_NEWEST                      1019
#define IDC_BRANCH                      1020
#define IDC_EXTDIFFBROWSE               1021
#define IDC_EXTMERGEBROWSE              1022
#define IDC_CHECK1                      1023
#define IDC_CHANGEDDIRS                 1023
#define IDC_ENABLE                      1023
#define IDC_MODULENAMECHECK             1023
#define IDC_SAVECHECK                   1023
#define IDC_ADDBEFORECOMMIT             1023
#define IDC_EDIT1                       1027
#define IDC_NAME                        1027
#define IDC_REVNUM                      1027
#define IDC_SERVERADDRESS               1027
#define IDC_TEMPEXTENSIONS              1027
#define IDC_REVISON_START               1027
#define IDC_URLCOMBO                    1029
#define IDC_COMBO1                      1030
#define IDC_BUTTON1                     1031
#define IDC_LOGBUTTON                   1031
#define IDC_RADIO1                      1032
#define IDC_REVISION_HEAD               1032
#define IDC_RADIO2                      1033
#define IDC_REVISION_N                  1033
#define IDC_REVISION_NUM                1034
#define IDC_BROWSE                      1035
#define IDC_EDIT2                       1036
#define IDC_BROWSE2                     1036
#define IDC_CHECKOUTDIRECTORY_BROWSE    1036
#define IDC_REPOS_TREE                  1037
#define IDC_SERVERPORT                  1038
#define IDC_USERNAME                    1039
#define IDC_PASSWORD                    1040
#define IDC_TIMEOUT                     1041
#define IDC_STATICURL                   1042
#define IDC_LIST1                       1043
#define IDC_FILELIST                    1043
#define IDC_ADDLIST                     1043
#define IDC_LANGUAGECOMBO               1044
#define IDC_FROMURL                     1045
#define IDC_COMMIT_TO                   1046
#define IDC_REMOVABLE                   1048
#define IDC_NETWORK                     1049
#define IDC_FIXED                       1050
#define IDC_CDROM                       1051
#define IDC_HINTLABEL                   1052
#define IDC_REVISION_END                1053
#define IDC_VERSIONABOUT                1054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
